### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#1]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://propublica.github.io/congress-api-docs/ So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by konklone** [comment]
Also, please consider going through other repos in this org (like the Campaign Finance API docs) and doing the same thing.

**Comment by dwillis** [comment]
Done.

**Comment by konklone** [comment]
Awesome, thanks! :smiley_cat:
