### ISSUE TITLE
index.html contains Slate error code boilerplate

### ISSUE THREAD

**Issue by renderorange** [propublica/congress-api-docs#10]
From line 6652 through the end in the index.html, it appears the error codes described are for the Slate examples; references to Kittn API, etc.

I'm happy to update the file with a merge request containing the proper supported error codes for your API, given a list of the codes.

thanks

**Comment by dwillis** [comment]
Thanks, @renderorange! We've updated that now.

**Comment by renderorange** [comment]
(thumbs up)
