### ISSUE TITLE
Document possible vote_type values

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#101]
In the Senate, this appears to be a fraction: `"1/2"`, `"3/5"`.

For the House, I've seen a few:

```
"YEA-AND-NAY"
"2/3 YEA-AND-NAY"
"RECORDED VOTE"
```

These should be documented, and it'd help to document what they specifically each mean.

**Comment by dwillis** [comment]
This has been added.

**Comment by konklone** [comment]
Yes it has, thank you!
