### ISSUE TITLE
Breaking bugs with Speaker election vote

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#102]
There are two issues with votes for election of the Speaker. The simplest one (to describe) is that fetching the vote itself gives a 500 error:

```
$ curl -s "https://api.propublica.org/congress/v1/115/house/sessions/1/votes/2.json" -H "X-API-Key: [redacted]"
{"status":"500","error":"Internal Server Error"}
```

Everything else in the above request is correct - changing `2.json` to `1.json` causes the quorum vote data to be displayed.

The second bug is that, when the Speaker election is listed in vote listing endpoints, people's specific vote results are dropped. The `total` field breaking down votes for House Vote No. 2 in 2017 is:

```json
           "total": {
             "yes": 239,
             "no": 189,
             "present": 0,
             "not_voting": 2
            }
```

This isn't accurate - the votes on House Vote No. 2 can be seen here:

http://clerk.house.gov/evs/2017/roll002.xml

Speaker votes are annoying as hell to represent, as they're so different and non-standard from the other votes. But, somehow, the number of votes each name got needs to be represented for the information to be accurate.

I haven't seen the detailed `positions` data for the Speaker election vote, because of the 500 error described above, but I would hope that the name of each member's individual vote is displayed there as well.

**Comment by jeremybmerrill** [comment]
@konklone the 500 is fixed... as to the yes/no count, it looks to me like it's coming in from the `hulse` gem that way, so it's probably better if we wait on Derek for this one.

**Comment by konklone** [comment]
I can verify the 500 is fixed. I think the yes/no count issue is significant, though, so yeah, would like @dwillis' thoughts on that.

**Comment by dwillis** [comment]
My thoughts: I think one way to handle this to generate party and total breakdowns based on the actual positions data. The issue is that it would be different from the documented vote response structure (and for nearly every Speaker vote).

**Comment by konklone** [comment]
Yes, you would basically have dynamic field names in the `totals` object, which you would need to document. I guess alternatively you could make the field structure more complicated, where you have an array of static field names with extra values, like:

```json
[{"vote_name": "Yea", "vote_count": 234"}, {"vote_name": "Ryan (WI)", "vote_count" 233}]
```

But yes, either way there's a bit of complexity. In the Sunlight API, I chose dynamic field names and documented and warned users. It was easy enough to not break folks' code, since if you just rely on yea/nay/nv/present being there it'll still work, there's just extra fields you'll drop.

In any case, I've worked around it in my client for now by walking through the positions one-by-one and assembling a totals field myself, at least for vote positions other than yea/nay/nv/present. 

But I wanted to flag that the `totals` field is inaccurate for Speaker votes, and that it's not obvious or documented for most users how clients should handle Speaker vote data.

**Comment by dwillis** [comment]
Is something like this workable for you? 
<img width="226" alt="screen shot 2017-08-23 at 11 34 00 am" src="https://user-images.githubusercontent.com/2214/29624419-0499a98c-87f7-11e7-88d5-2ab8a92ac72e.png">

**Comment by konklone** [comment]
That would totally do it.

**Comment by dwillis** [comment]
This is done: https://api.propublica.org/congress/v1/115/house/sessions/1/votes/2.json

**Comment by konklone** [comment]
Thank you!
