### ISSUE TITLE
Include the vote result and a "totals" breakdown for member position list

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#103]
On the endpoint to [get a member's vote positions](https://projects.propublica.org/api-docs/congress-api/endpoints/#get-a-specific-members-vote-positions), it has many fields about the vote that the member was participating in.

However, it's missing the `results` and `totals` fields, which would be very helpful in displaying a member's vote directly in the context of how/whether a vote succeeded.

**Comment by konklone** [comment]
This appears to be resolved, and the fields added. Did you add these?

**Comment by dwillis** [comment]
Yes, sorry. Forgot to update here.

**Comment by konklone** [comment]
Looks fixed to me, thank you!
