### ISSUE TITLE
Get Amendments for a bill documentation is wrong

### ISSUE THREAD

**Issue by lafritay** [propublica/congress-api-docs#107]
The current docs for getting a specific bill's amendments claim to return a payload that looks like this:

![image](https://user-images.githubusercontent.com/438824/29191168-d4aa2fd2-7dea-11e7-9410-23c71c611b2a.png)
![image](https://user-images.githubusercontent.com/438824/29191187-e74b117e-7dea-11e7-8095-7f54e33ef865.png)

When we make the requests, we see this:

![image](https://user-images.githubusercontent.com/438824/29191200-f0c35d06-7dea-11e7-9762-dd1228be779b.png)

Note, Subjects and Related follow the spec.  Which is correct?

**Comment by dwillis** [comment]
@lafritay We've updated our docs to fix this: https://projects.propublica.org/api-docs/congress-api/bills/#get-amendments-for-a-specific-bill

**Comment by lafritay** [comment]
Thanks!
