### ISSUE TITLE
Request: Bills and Nominations by introduced date 

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#109]
Would make it easier to cache the data on my own server.  If there is a current way to do this, please let me know.

**Comment by dwillis** [comment]
You can get bills by introduced date (paginated, 20 at a time), using the request described here: https://projects.propublica.org/api-docs/congress-api/endpoints/#get-recent-bills and setting the `type` value as `introduced`.

Similarly, for nominations you can get recently received nominations (since they are not introduced by members of Congress like bills are) using the request here: https://projects.propublica.org/api-docs/congress-api/endpoints/#get-recent-nominations-by-category and setting `type` to `received`.

**Comment by epanchenko** [comment]
How do I know I got all of the bills?  How do I specify page 2, page 10?

**Comment by dwillis** [comment]
One way would be to set up a loop, incrementing by 20 until you get a results array with no results in it, at which point you've got the whole set.

We are close to having a bulk download option for bills that mirrors what's here: https://github.com/unitedstates/congress/wiki

The format differs from the ProPublica Congress API, but it contains substantially similar information.

**Comment by epanchenko** [comment]
Can you provide me an example 2nd call that I can specify page 2?  What does "pagination is available via an offset query string parameter" exactly refer to?  Thanks.

**Comment by dwillis** [comment]
Sure: you can use the `offset` query string parameter like this:

`https://api.propublica.org/congress/v1/115/house/bills/introduced.json?offset=20`

That would give you the equivalent of "page 2". You can use any multiple of 20 as the offset value.

**Comment by epanchenko** [comment]
The offset value does not seem to stop for a long time.  I made it to offset 5000 for https://api.propublica.org/congress/v1/115/both/bills/introduced.json?offset=5000 and it was still showing bills from February.  I will stop it myself by looking at dates instead of relying on the num_results field, but it would be nice if we could pass in a date and it would just return the bills for that date.

**Comment by dwillis** [comment]
That's true, and I think we can work out a bills by date response. Also, this week we'll be announcing a resumption of the bulk bill metadata downloads, which might help.

**Comment by dwillis** [comment]
@epanchenko https://www.propublica.org/nerds/bulk-downloads-of-congressional-data-now-available might be of use.
