### ISSUE TITLE
Include vice president's vote on Senate tie-breakers

### ISSUE THREAD

**Issue by bycoffe** [propublica/congress-api-docs#11]
On Senate vote responses, it would be useful to know how the vice president voted in cases where the Senate vote is tied.

An example URL is: https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/54.json

The [XML from the Senate](https://www.senate.gov/legislative/LIS/roll_call_votes/vote1151/vote_115_1_00054.xml) includes a `tie_breaker` node, with values for `by_whom` and `tie_breaker_vote`.

**Comment by dwillis** [comment]
Resolved by e0bc9617182987143f840bb53466c18cd47c2832
