### ISSUE TITLE
Add chair info to committee detail response

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#114]
The committee listing endpoint has `chair`, `chair_state`, `chair_party`, and `chair_id` fields, but the committee details endpoint only has `chair_id`. It'd be helpful to have the other 3 fields on the committee details response as well.

**Comment by konklone** [comment]
(Edited above to note it's `chair` instead of the mistaken `chair_name`.)

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Verified, thank you!
