### ISSUE TITLE
Consistent field name for committee name

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#115]
On the committee listing endpoint, it's `name`, but on the committee details endpoint, it's `committee`.

This is particularly confusing since the committee listing and details endpoints are documented as a single endpoint.

**Comment by dwillis** [comment]
It should be `name` on both; we'll fix.

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
Verified, thank you!
