### ISSUE TITLE
Document committee detail endpoint, maybe put into separate documentation

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#116]
The committee listings endpoint and the committee details endpoint have very different schemas and structures, but they're currently only documented as one endpoint. And only the committee listings endpoint is shown and explained.

It'd be better to separate these out and document them each individually.

**Comment by dwillis** [comment]
This is done:
https://projects.propublica.org/api-docs/congress-api/endpoints/#lists-of-committees
https://projects.propublica.org/api-docs/congress-api/endpoints/#get-a-specific-committee

**Comment by konklone** [comment]
Nice, thank you!
