### ISSUE TITLE
Include reliable majority/minority status for committee membership/ranking

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#119]
Here's an example of a committee detail response:

```json
      {
         "congress": "115",
         "chamber": "House",
         "committee": "Committee on Agriculture",
         "url": "https://agriculture.house.gov/",
         "num_results": 46,
         "chairman_id": "C001062",
         "ranking_member_id": "P000258",
         "current_members": [
              {
                 "id": "P000258",
                 "name": "Collin C. Peterson",
                 "api_uri":"https://api.propublica.org/congress/v1/members/P0002
58.json",
                 "party": "D",
                 "rank_in_party": "1",
                 "state":"MN",
                 "note": "",
                 "begin_date":""
               },
```

Each member has their `rank_in_party`, and it appears that memberships are listed in pairs, but the pairs don't have any particular ordering (the above committee goes [1D, 1R, 2R, 2D]). The committee information doesn't say what party is in control of the committee.

So there's no way to reliably determine whether a member of the committee is on the majority or minority side, and no way to reliably order members.

In the Sunlight API, we had a `members` field on committees that looked like this:

```json
"members": [
    {
      "side": "majority",
      "rank": 1,
      "title": "Chair",
      "legislator": {
        "bioguide_id": "K000210",
        "chamber": "house"
        ...
      }
    }
    ...
  ]
```

The `side` and `title` fields would be very helpful there, in determining at parse-time what relationship a member has to the committee.

**Comment by konklone** [comment]
Also, having a generic `rank` field instead of only `rank_in_party` would help to reliably order the committee members.

**Comment by dwillis** [comment]
We'll add `side` and a note to the documentation that indicates a `rank` of 1 on the majority side is the chair (and on the minority side the ranking member). My concern with a generic `rank` field is that without the party element it could be misleading. The ranking minority member is not considered the (for example) 21st in rank in a committee with 20 majority members.

**Comment by dwillis** [comment]
We've added `side` to the committee membership.

**Comment by konklone** [comment]
> My concern with a generic `rank` field is that without the party element it could be misleading. The ranking minority member is not considered the (for example) 21st in rank in a committee with 20 majority members.

Right - a generic `rank` field should represent the actual rank. But, hmm, looking at a Sunlight Congress API response, maybe I didn't order them that way:

http://congress.api.sunlightfoundation.com/committees?per_page=1&fields=members

Looks similar to Pro Publica, where it's actually a rank within the `side`. Oh well. I'm considering this resolved, then!
