### ISSUE TITLE
No way to fetch subcommittee memberships?

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#121]
I can't figure out how to get the members of a subcommittee. Supply a subcommittee ID instead of a committee ID on the details endpoint doesn't work. Is it possible to get subcommittee memberships?

**Comment by dwillis** [comment]
There is now: https://projects.propublica.org/api-docs/congress-api/endpoints/#get-a-specific-subcommittee

**Comment by konklone** [comment]
That does it, thank you!
