### ISSUE TITLE
Chamber on bill actions wrong with type is President

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#123]
I would think the chamber should be blank once a bill is acted on by the President.

 "actions":[
         {
           "id": 36,
           "chamber": "House",
           "action_type": "President",
           "datetime": "2017-08-12",
           "description": "Became Public Law No: 115-46."
         },
                  {
           "id": 35,
           "chamber": "House",
           "action_type": "President",
           "datetime": "2017-08-12",
           "description": "Signed by President."
         }

https://api.propublica.org/congress/v1/115/bills/s114.json

**Comment by dwillis** [comment]
That seems a reasonable expectation. We'll fix.

**Comment by dwillis** [comment]
This should be fixed this evening.

**Comment by epanchenko** [comment]
It is fixed.
