### ISSUE TITLE
Calling subcommittee getting internal server error

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#124]
https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG03.json
{"status":"500","error":"Internal Server Error"}

**Comment by dwillis** [comment]
HAG03 isn't a valid code for a subcommittee, but HSAG03 is, based on subcommittee list here: https://api.propublica.org/congress/v1/115/house/committees/HSAG.json

**Comment by epanchenko** [comment]
The following is what I get for HSAG, there are ids that start HAG:

https://api.propublica.org/congress/v1/115/house/committees.json
"id": "HSAG",
                 "name": "Committee on Agriculture",
                 "chamber": "House",
                 "url": "https://agriculture.house.gov/",
                 "api_uri":"https://api.propublica.org/congress/v1/115/house/committees/HSAG.json",
                 "chair": "K. Michael Conaway",
                 "chair_id": "C001062",
                 "chair_party": "R",
                 "chair_state": "TX",
                 "chair_uri": "https://api.propublica.org/congress/v1/members/C001062.json",
                 "ranking_member_id": "P000258",
                 "subcommittees": [
                  {
                    "id": "HSAG03",
                    "name": "Nutrition",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG03.json"
                  },
                                {
                    "id": "HSAG16",
                    "name": "General Farm Commodities and Risk Management",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG16.json"
                  },
                                {
                    "id": "HSAG15",
                    "name": "Conservation and Forestry",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG15.json"
                  },
                                {
                    "id": "HSAG22",
                    "name": "Commodity Exchanges, Energy, and Credit",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG22.json"
                  },
                                {
                    "id": "HSAG29",
                    "name": "Livestock and Foreign Agriculture",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG29.json"
                  },
                                {
                    "id": "HSAG14",
                    "name": "Biotechnology, Horticulture, and Research",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HSAG14.json"
                  },
                                {
                    "id": "HAG03",
                    "name": "Nutrition",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG03.json"
                  },
                                {
                    "id": "HAG16",
                    "name": "General Farm Commodities and Risk Management",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG16.json"
                  },
                                {
                    "id": "HAG15",
                    "name": "Conservation and Forestry",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG15.json"
                  },
                                {
                    "id": "HAG22",
                    "name": "Commodity Exchanges, Energy, and Credit",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG22.json"
                  },
                                {
                    "id": "HAG29",
                    "name": "Livestock and Foreign Agriculture",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG29.json"
                  },
                                {
                    "id": "HAG14",
                    "name": "Biotechnology, Horticulture, and Research",
                    "api_uri": "https://api.propublica.org/congress/v1/115/house/committees/HSAG/subcommittees/HAG14.json"
                  }

**Comment by dwillis** [comment]
@epanchenko Yeah, I see. We'll fix.

**Comment by dwillis** [comment]
Ok, this should be resolved now.

**Comment by epanchenko** [comment]
ok it is resolved.
