### ISSUE TITLE
Include subcommittees in committee memberships

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#126]
The `committees` field inside of the `roles` array on the legislator details endpoint would benefit from including subcommittees. It's not otherwise clear how to get easily a list of subcommittees someone belongs to.

**Comment by dwillis** [comment]
We've added this tonight.

**Comment by konklone** [comment]
Thank you! However, since they were added as a separate flat list they are difficult to use without containing a reference to their parent committee ID in each object. (Otherwise, we get into the question in #143, where a client has to infer the parent committee ID by assuming that the first four characters of the subcommittee ID are the committee ID.)

Could you add a `parent_committee_id` field to each object in the `subcommittees` array on the legislator details endpoint?

**Comment by dwillis** [comment]
This is done now.

**Comment by konklone** [comment]
Verified and implemented! But just noting that the doc example for the member endpoint doesn't reflect the addition of subcommittees:

https://projects.propublica.org/api-docs/congress-api/members/#get-a-specific-member

**Comment by dwillis** [comment]
Example is updated now.
