### ISSUE TITLE
Include chamber field for committees in memberships

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#128]
The `committees` array inside the `roles` array on the legislator details endpoint lacks `chamber` fields, so they have to be inferred by looking at the first character of the string of the committee ID. It'd be simpler to have it as a field, like it is on the committee endpoints.

**Comment by dwillis** [comment]
@konklone But the `chamber` is on the `roles` array itself; is that not sufficient?

**Comment by konklone** [comment]
Not for `Joint` committees.

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Verified and implemented, thanks!
