### ISSUE TITLE
source to text of bill amendments

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#132]
Using https://api.propublica.org/congress/v1/115/bills/hr1628/amendments.json as an example, is it possible to have a field that has a pdf link to the text of the amendment?  If not the amendment, something that talks about the amendment?  Some of the titles are blank on the amendments.

https://www.congress.gov/amendment/115th-congress/senate-amendment/729 is an example that eventually points to some info about the amendment (in a round about way) that a user can read...I am not sure if the URLs are consistent for all types of bills.

**Comment by dwillis** [comment]
That makes sense, sure. We've added a `congressdotgov_url` to amendment responses.

**Comment by epanchenko** [comment]
Thanks.
