### ISSUE TITLE
Support for the Commission on Security and Cooperation in Europe

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#135]
Though it's not created as a formal committee, the [Commission on Security and Cooperation in Europe](https://en.wikipedia.org/wiki/Commission_on_Security_and_Cooperation_in_Europe) is treated as a committee by at least the Senate and has joint membership among the House and Senate:

https://www.senate.gov/pagelayout/committees/b_three_sections_with_teasers/membership.htm

It's in https://github.com/unitedstates/congress-legislators/blob/master/committees-current.yaml as a current committee as well, and it's included as a `joint` committee in the Sunlight API.

Not saying this is the most urgent thing in the world, and it is a weird case, but wanted to flag this as something potentially missing.

**Comment by epanchenko** [comment]
This one does come up in Sunlight as a committee.

**Comment by dwillis** [comment]
This is now in the API as a committee: https://api.propublica.org/congress/v1/115/senate/committees/JCSE.json

**Comment by konklone** [comment]
It doesn't appear to show up yet when listing joint committees, is that expected?

**Comment by dwillis** [comment]
This is done.
