### ISSUE TITLE
Committee on House Administration name is missing "House"

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#136]
The Pro Publica API has it as "Committee on Administration", but it's "Committee on House Administration":

Sources:

* http://clerk.house.gov/committee_info/scsoal.pdf
* https://cha.house.gov/
* http://clerk.house.gov/committee_info/index.aspx

**Comment by dwillis** [comment]
This is fixed & should be in API responses shortly.

**Comment by konklone** [comment]
Confirmed, thanks!
