### ISSUE TITLE
Support for United States Senate Caucus on International Narcotics Control

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#138]
Same as #135, but for the United States Senate Caucus on International Narcotics Control.

https://www.senate.gov/general/committee_membership/committee_memberships_SCNC.htm

**Comment by dwillis** [comment]
This is now done in the API: https://api.propublica.org/congress/v1/115/senate/committees/SCNC.json

**Comment by konklone** [comment]
Same as #135, this doesn't yet appear to show up in lists of Joint committees.

**Comment by dwillis** [comment]
I'm not sure it should; it's a Senate caucus. It is listed among the Senate committees.

**Comment by konklone** [comment]
Whoops, you are right. :+1:
