### ISSUE TITLE
Committee chamber field is set by URL and not by the data

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#139]
When accessing a joint committee, it can be accessed with any `chamber` in the URL, and the `chamber` field is populated by the URL rather than the data in the database:

For example:
https://api.propublica.org/congress/v1/115/house/committees/JSPR.json

Has a `chamber` field of `House` in the response. This can also be done with Senate/House committees. For example, this will show a `chamber` of `Senate` for a House committee:

https://api.propublica.org/congress/v1/115/senate/committees/HSAG.json

**Comment by dwillis** [comment]
This is fixed.
