### ISSUE TITLE
Give committee members a chamber field

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#140]
On Joint committees, there's no way to tell which chamber a member is in at parse-time. It would be helpful to add a `chamber` field to members of a given committee, identifying which chamber they are from.

It would be helpful to do this on all committees, not just joint committees, but it's necessary for joint committees.

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Verified and implemented, thanks!
