### ISSUE TITLE
Joint committees have incorrect ranking info and title structure

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#142]
The Joint Committee on Taxation has a Chair of Kevin Brady (which the PP API is correct on), but has a Vice Chair of Orrin Hatch (which isn't reflected in the PP API):

https://www.jct.gov

The PP API lists Kevin Neal as the ranking member (via the `ranking_member_id` field). However, there is no ranking member of this committee that I can see.

Ideally, committees would provide a `title` or `committee_title` field on each membership entry, so that the person's title relative to the committee they are a member of is clear.

**Comment by konklone** [comment]
The Joint Committee on Printing and Joint Committee on the Library are the same way:

* https://cha.house.gov/jointcommittees/joint-committee-on-printing
* https://cha.house.gov/jointcommittees/joint-committee-library

**Comment by dwillis** [comment]
The memberships of the joint committees are a less-than-well-documented thing, but I don't think I agree with your characterization here. Many committees have Vice Chairs (see [House Rules](https://rules.house.gov/committee-rules-members)), who are typically the 2nd-ranking member of the majority party. The ranking member of the minority party is the ranking member regardless of whether that's an official title or not.

We will fix the rank_in_party values, and Orrin Hatch's would be 2, as he is the second-ranking member of the majority party, while Richard Neal's would be ranking minority member.

**Comment by konklone** [comment]
> More generally, committee memberships are so poorly kept (in terms of timeliness and accuracy) both by official sources and unofficial that the addition of attributes, while desirable, also could lead to more inaccurate information.

This stuff is handled inside the @unitedstates `congress-legislators` repo, though:
https://github.com/unitedstates/congress-legislators/blob/master/committee-membership-current.yaml

I've been hand-checking committee information between Pro Publica and Sunlight (which just grabs straight from the `congress-legislators` repo) and the congress-legislators data has been correct in all but one case - listing Paul Ryan as Chair of the Joint Committee on Taxation.

**Comment by dwillis** [comment]
I think @unitedstates does a good a job as possible with _current_ memberships, but not for _all_ memberships. Case in point: Tim Walz was a member of the House Armed Services Cmte for 2 days this year.

**Comment by konklone** [comment]
OK, then since the null rank fields are covered in #141, I think this can be closed if no further action is desired. I am not sure how to programmatically display that Orrin Hatch is the Vice Chair for JCT without JCT-specific code in my client, though.

**Comment by dwillis** [comment]
I could be cheeky and point out that even [Orrin Hatch](https://www.hatch.senate.gov/public/index.cfm/committee-assignments) doesn't acknowledge that he's a member of the JCT, much less the vice chair. But let me think about how we can do this reliably. Updating committee info to be as accurate and comprehensive as possible is not a simple task.

**Comment by konklone** [comment]
> Updating committee info to be as accurate and comprehensive as possible is not a simple task.

Totally understood. One option would be to use @unitedstates data for current assignments (which would address this for clients that only care about current data), and use other sources for historic assignments.

**Comment by dwillis** [comment]
Yep, although @unitedstates isn't current - it has no assignments for Ron Estes, for example, and incorrect ones for John Sarbanes and a few others. I'll be submitting PRs for this hopefully shortly, but it underscores the difficulties of maintaining even a current set.

**Comment by dwillis** [comment]
Joint committee ranking information is fixed now.
