### ISSUE TITLE
Question: safe way to distinguish subcommittees from committees by ID?

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#143]
Is it safe to assume that all committee IDs are, and will remain, 4 characters long? 

Since the subcommittee endpoint and committee endpoint use different URL structures, I sometimes have to know which one to request. If this isn't safe, I'll see if I can find an alternate way.

**Comment by konklone** [comment]
> Is it safe to assume that all committee IDs are, and will remain, 4 characters long?

Sorry, and importantly -- is it also safe to assume that **no** subcommittee IDs are 4 characters long? That they will always be longer than 4?

**Comment by dwillis** [comment]
I'm not sure I follow. Subcommittee urls have `subcommittee` in them, whereas committee urls do not.

**Comment by konklone** [comment]
Right, but I mean that, given only a committee ID, can I tell whether I need to fetch more details at the committee endpoint, or the subcommittee endpoint?

I've been working on this more since filing it, and it may not end up being as necessary as I thought -- I think I always have access to a boolean fact of whether it's a subcommittee or not at decision-time. Still might be an interesting question to answer for other clients, though.

**Comment by dwillis** [comment]
Would a field like `type`: `committee` or `type': `subcommittee` be helpful?

**Comment by konklone** [comment]
No, because that implies I have access to the full set of committee data to get that field at the time. This would only be useful if all I have is the ID.

**Comment by konklone** [comment]
If it's not safe, I think that's fair to say -- I've already figured out how to handle this (it turns out I did consistently have access to info beyond the ID) and have moved on.

**Comment by dwillis** [comment]
Ok. I'm not sure that it's unreasonable to have clients store committee lists, but would be willing to revisit that.

**Comment by konklone** [comment]
> Ok. I'm not sure that it's unreasonable to have clients store committee lists, but would be willing to revisit that.

I would say that that's unreasonable for native mobile clients where local storage is complicated, and background actions are expensive and tricky. Clients in those cases have a significantly constrained API they have to deal with, and managing data offline can add substantial client complexity. Obviously it's possible, but in my case I only do it on user-supplied actions for specific members/bills (which is relatively simple and targeted), rather than trying to keep a large local dataset in sync that informs my interactions with the API (which would be very complicated).

However, in this case, my client always enters into subcommittee views from a place where that subcommittee's been serialized and can be passed ephemerally from one screen to another, making this unnecessary.
