### ISSUE TITLE
Missing subcommittees on Senate committees

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#144]
The Senate Committee on Agriculture, Nutrition, and Forestry shows up as having 0 subcommittees:

https://api.propublica.org/congress/v1/115/senate/committees/SSAF.json

But it has 5:
https://www.agriculture.senate.gov/about/subcommittees

**Comment by konklone** [comment]
Broadly speaking, it looks like the PP API is missing subcommittees for Senate committees in general.

**Comment by dwillis** [comment]
This is a bug with data loaders and we'll fix. We had them last week.

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
@dwillis It looks like this issue has regressed - I can't get subcommittees for any Senate committee (empty array, as before).
