### ISSUE TITLE
URL/domain info for some members seems inconsistent

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#145]
As an example, here are three fields for Edward Royce, with varying hostnames and protocols:

```json
         "url": "http://royce.house.gov",
         "rss_url": "https://royce.house.gov/news/rss.aspx",
         "domain": "www.royce.house.gov",
```

**Comment by dwillis** [comment]
We'll fix the `url` for Royce. The domain is used as part of ProPublica's own processes; we can omit it if you think having it is problematic.

**Comment by konklone** [comment]
> The domain is used as part of ProPublica's own processes; we can omit it if you think having it is problematic.

I don't think it's problematic, but I just wanted to flag it in case that wasn't expected. I was flagging the use of `www.` for that field, not the lack of a protocol. `www.royce.house.gov` doesn't seem to be the canonical domain for Rep. Royce.

**Comment by dwillis** [comment]
Very true.

**Comment by dwillis** [comment]
Ok, we've updated the `url` values and have removed the `domain` attribute from member responses, since they are not maintained in the same way and serve a specific purpose for us.
