### ISSUE TITLE
Member's vote positions isn't paginated as expected

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#147]
The member's specific vote positions endpoint returns an `offset` field, but doesn't seem to respond to `offset` parameters. Instead, it returns the latest 100 votes.

I am not sure whether it's currently intended to be a paginated endpoint, but if not, I request it be one. That would be the easiest way to deal with parsing and watching someone's votes over time, and it would be consistent with other endpoints in the API.

**Comment by dwillis** [comment]
Yep, we'll make it paginated using offsets of 20 like the others.

**Comment by dwillis** [comment]
This is done.
