### ISSUE TITLE
Returned Member titles are inconsistent with Sunlight results

### ISSUE THREAD

**Issue by jalefkowit** [propublica/congress-api-docs#155]
When you got a Member's information back from the old Sunlight Congress API, the `title` field contained the Member's official title in an abbreviated format: "Sen", "Rep", "Del" or "Com".

The equivalent call to the new Congress API returns the Member's title as well in their `roles`, but does so in a full rather than abbreviated format: "Representative" instead of "Rep", for instance. For Senators it also includes class information ("Senator, 1st Class") which is extraneous information if you just need a chamber-agnostic field to look at to find how they should be referred to. (In other words, if you just take the new-style `title` you get names formatted like "Senator, 2nd Class Cory  Booker.")

This makes migration from the Sunlight API harder, as you can't just take the `title` you get back now and drop it into the places you used the old `title`.

Is there some alternate place to look in the results if you want the abbreviated titles the old Sunlight API returned? Or some alternate endpoint/special header/etc. to use?

**Comment by dwillis** [comment]
We've added a `short_title` attribute to the member lists and member detail responses. Will be live later today.

**Comment by dwillis** [comment]
@jalefkowit does this addition work for you?

**Comment by jalefkowit** [comment]
Yep, it sure does! Thanks!
