### ISSUE TITLE
Recent bills endpoint offset

### ISSUE THREAD

**Issue by jelenaDedskin** [propublica/congress-api-docs#158]
Offset parameter is not working for recent bills endpoint, for {chamber} set to both. It's ignored, and page for offset=0 is always returned. And for {chamber} set to house or senate it has really strange behaviour , like it has some caching for first request

**Comment by dwillis** [comment]
@jelenaDedskin this should be fixed now.

**Comment by jelenaDedskin** [comment]
Thanks, confirmed!
