### ISSUE TITLE
Missing keywords in Bills API response

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#159]
Now that the Sunlight API has officially ended (October 1st), are there any plans to include bill keywords in the JSON response, as Sunlight did?

**Comment by dwillis** [comment]
Hi @mininternet: what Sunlight called keywords, we call subjects and have included them in the ProPublica Congress API since its inception. https://projects.propublica.org/api-docs/congress-api/bills/#get-subjects-for-a-specific-bill

**Comment by mininternet** [comment]
@dwillis  - Excellent! I see them now, was concerned I'd have to strip out that functionality.

Feel free to take a look, have an educational Congressional BI dashboard online now - www.whogovernsus.org. In the process of adding Bills and Votes back in. 

Thanks again for all the hard work.

**Comment by mininternet** [comment]
Ah, I just noticed the endpoint is for subject for a specific bill.

Is there no way to include subjects as a field in the bills API endpoint, in a similar manner to how Sunlight allowed fields to be defined in the GET request?

**Comment by dwillis** [comment]
We do put a bill's `primary_subject` in the bill list responses, but since bills can have multiple subjects (as the example from the docs shows) I'm reluctant to put them all in those responses.

**Comment by mininternet** [comment]
Understood. I'm just curious if is possible to request that column (or others) to generate a dynamic response, rather than just the standard boilerplate JSON response. 

That was one of the most powerful features of the Sunlight API - essentially writing your own SELECT statements.

**Comment by dwillis** [comment]
Unfortunately, that's not an option we could preserve due to the underlying architecture decisions we made in our API (which have a lot of benefits, but also some drawbacks like this). Can I ask in what context you find yourself needing that information? Is it all bills or a custom set?

**Comment by mininternet** [comment]
Here are examples of what I was displaying using the Sunlight API - 

![legislator_bills_no_overlay](https://user-images.githubusercontent.com/3261696/31157010-81e7816a-a87d-11e7-9160-2d725fd58341.png)

![ex_bill_keywords_chart](https://user-images.githubusercontent.com/3261696/31157024-8fc490c0-a87d-11e7-99c4-31d730764767.png)


Every Bill had a toggle between the Official Title, and a Keywords option (labeled as TLDR in the image), to give a quick summary of what the Bill was about.

Before those keywords were coming in per Bill, so no need for a separate call. 

The second image shows a simple chart breakdown of all keywords of the Bills that individual legislator has sponsored (introduced). It was very convenient to pull those in and visualize in a single call. Now would require iterating over every Bill, which is costly.

The ability to quickly highlight what keywords (subjects) a particular legislator was primarily concerned with seemed fairly informative, based on initial testing.

**Comment by mininternet** [comment]
It's fine, I can work around this issue, just need to explore the API a bit further  - will have a couple of other questions I'm sure. 

Thanks again!
