### ISSUE TITLE
Specific member's committee title and side

### ISSUE THREAD

**Issue by pll33** [propublica/congress-api-docs#160]
Back in the Sunlight API, there was a way to find out the [titles of committee members](https://sunlightlabs.github.io/congress/committees.html#members) through the `/committees` endpoint. 

In the ProPublica API, [Lists of Committees](https://projects.propublica.org/api-docs/congress-api/other/#lists-of-committees) and [Get a Specific Committee](https://projects.propublica.org/api-docs/congress-api/other/#get-a-specific-committee) will return `chair_id`, `ranking_member_id`, `rank_in_party` (sometimes `null` unless they're chair/ranking member), and the `side` (minority or majority). Meanwhile `rank_in_party` seems to always have a non-null value in [Get a Specific Subcommittee](https://projects.propublica.org/api-docs/congress-api/other/#get-a-specific-subcommittee).

With the Sunlight API, I made a single call to `/committees` to find out a specific members' committees then listed them with their committee title in ascending order by rank number. However there's no easy way to do this here in the ProPublica API without numerous calls - first to get a specific member, then a call for each committee and subcommittee to check if their legislatorID matches the chair or ranking member ID, or if their rank is null or "not 1" which makes them a normal member. 

(this is without making the assumption that a particular party is in the minority/majority because that may change from Congress session to session)

Sunlight API call:
```
https://congress.api.sunlightfoundation.com/committees?member_ids=' + legId + '&fields=name,chamber,url,subcommittee,members.legislator.bioguide_id,members.title,members.rank
```

A snippet of Amy Klobuchar's (K000367) committees/subcommittees for example through the ProPublica API

```
"committees": [
    {
        "name": "Committee on Rules and Administration",
        "code": "SSRA",
        "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSRA.json",
        "rank_in_party": 1,
        "begin_date": "2017-01-03",
        "end_date": "2019-01-03"
    }
],
"subcommittees": [
    {
        "name": "Conservation, Forestry and Natural Resources Subcommittee",
        "code": "SSAF14",
        "parent_committee_id": "SSAF",
        "api_uri": "https://api.propublica.org/congress/v1/115/senate/committees/SSAF/subcommittees/SSAF14.json",
        "rank_in_party": 3,
        "begin_date": "",
        "end_date": "2019-01-03"
    }
]
```

It just seems like a lot of unnecessary calls to get a minimal amount of information so I'm wondering if it's possible to add a `title` (chair, ranking member, member, etc.) and/or `side` (minority, majority) to the objects within members' committees and subcommittees in ["Get a Specific Member"](https://projects.propublica.org/api-docs/congress-api/members/#get-a-specific-member)

At the very least, adding `side` would help along with the existing `rank_in_party` to figure out the member title. 

i.e.
```
If rank_in_party = 1 and side = majority then 'Chair'
Elseif rank_in_party = 1 and side = minority then 'Ranking Member'
Else 'Member'
```

Also some committees have a vice chair instead which may or may not be in the same party as the majority (e.g. [Joint Committee on Taxation](https://en.wikipedia.org/wiki/United_States_Congress_Joint_Committee_on_Taxation)) which adds some complexity where having `title` as well would help.

**Comment by dwillis** [comment]
Thanks, @pll33. We can add `side` and `title` to the Get a Specific Member responses.

**Comment by pll33** [comment]
Thanks for the speedy response!

**Comment by dwillis** [comment]
@pll33 For now, we've added `side` and `title` attributes for committee memberships covering the 115th congress. We'll work to backfill previous congresses; in the meantime those attributes won't be present in the response.
