### ISSUE TITLE
Commitee IDs (thomas_id) in Bill JSON response?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#161]
Is there a reason full Committee names are returned in Bill responses, rather than Committee IDs, as with Sunlight?

I've noticed a couple of name discrepancies due to full text (i.e. House Committee on the Judiciary vs. House Judiciary Committee), plus IDs would seem more convenient for subsequent API calls.

ex: api.propublica.org/congress/v1/115/house/committees/**HSRU**/hearings.json

If not, is the Committees column an array (or comma delimited string) of names that have to be cross referenced against the Committees endpoint?

**Comment by dwillis** [comment]
@mininternet please do!
