### ISSUE TITLE
Cosponsors_by_Party in Bills JSON response?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#163]
Previously with Sunlight, it was possible to return a simple breakdown of Cosponsors by Party, per Bill, which helped for quickly visualizing partisanship. 

![bills_closeup](https://user-images.githubusercontent.com/3261696/31320851-19a66072-ac41-11e7-9742-e086253f64fa.png)

Now I only see this node present in the cosponsors endpoint. Would it be possible to add these two values to the Bills endpoint?

ex:
```
cosponsors_by_party: [
    {
      "party": {
        "id": "D",
        "sponsors": "18"
      }, {
        "id": "R",
        "sponsors": "7"
      }
    }
]
```
Reaching out to the cosponsors endpoint, per Bill, causes a 4 second operation to now take 29 seconds.

**Comment by dwillis** [comment]
I think we can add those values. Would it be simpler to have something like:

```
cosponsors_by_party: {
   "R" : 7,
   "D": 18
}
```

**Comment by mininternet** [comment]
Yes, absolutely. Anything to keep the json response size minimized always helps.
Thanks again!

-------- Original message --------

**Comment by dwillis** [comment]
This will be in the API this evening.

**Comment by mininternet** [comment]
I'm sorry, but is it possible to add that cosponsors_by_party node to the Introduced endpoint?

ex:
https://api.propublica.org/congress/v1/members/W000812/bills/introduced.json

I can create a separate ticket if it helps.

**Comment by dwillis** [comment]
This is done now.

**Comment by mininternet** [comment]
Great, i see it now.

Thanks again!
