### ISSUE TITLE
Members listed by chamber are almost, but not quite, in order

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#164]
When fetching members from a particular chamber, the members are listed in order of last name, but it's not correctly alphabetized. The first letter is correctly alphabetized, but not after that. For example, members of the House:

```
Aderholt
Amash
Amodei
Adams
Aguilar
Allen
Abraham
Arrington
```

It seems to be fine when listing members by state.

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
Confirmed, and thank you!
