### ISSUE TITLE
create https://api.propublica.org/congress/v1/members/current.json

### ISSUE THREAD

**Issue by irjudson** [propublica/congress-api-docs#166]
To return the list of all MoC's as the sunlight api did here: 

https://congress.api.sunlightfoundation.com/legislators?per_page=all

**Comment by dwillis** [comment]
We do this on a per-chamber basis: https://projects.propublica.org/api-docs/congress-api/members/#lists-of-members

**Comment by irjudson** [comment]
Right, I see that. But from a migratory point of view, you've entirely changed the work apps have to do to process all MoC's -- when the cost to put a simple veneer over what you have is so small it makes me wonder why?

**Comment by dwillis** [comment]
Mainly because the ProPublica API already existed prior to our taking over the Sunlight API, and in taking over and then absorbing the Sunlight Congress API we preferred to focus on the parts that we didn't have at all rather than re-do those that we do offer, albeit not in an identical manner. We made similar decisions in regards to bills and votes. You're also the first person to raise this issue with us; it's not something we considered outside of our general preference not to re-do existing responses.

**Comment by irjudson** [comment]
First by definition, I looked for an issue to +1 it :)

So is it a feature request you'll consider or ?

**Comment by dwillis** [comment]
We've heard from a decent amount of Sunlight users, so that no one else has asked for it kinda says something to me. I'm willing to consider it, but can you explain why making 2 calls instead of one would entirely change the work you have to do?

**Comment by dawaltconley** [comment]
Correct me if I'm wrong, but isn't the query for current members on a per-state-per-chamber basis? I haven't found a way to get current mems for an entire chamber unless you know the congress number.

I've been currently doing this by doing:

1. Get current mems from an arbitrary state
2. Follow the `api_uri` to get specific data for one of those mems and pull the congress number from their most recent `role`.
3. Then use that to list all current mems in a chamber.

That's only three queries but they also have to be synchronous. Sorry for reviving this old issue but I'm not sure if I'm just missing a basic feature. If I'm not and it's reasonable, then I'd open a separate feature request for the functionality you describe, something like `GET https://api.propublica.org/congress/v1/members/{chamber}/current.json`, or just a way to get the current congress num in one call.
