### ISSUE TITLE
500 response for cosponsors of HJ-Res 53

### ISSUE THREAD

**Issue by KristieDC** [propublica/congress-api-docs#167]
`GET https://api.propublica.org/congress/v1/115/bills/hjres53/cosponsors.json` 

500 internal server error is returned for the cosponsor endpoint of HJ-Res 53.

**Comment by dwillis** [comment]
Thanks @KristieDC  - this should be fixed now.

**Comment by KristieDC** [comment]
Thanks @dwillis
