### ISSUE TITLE
Sponsor_ID (bioguide) in Bills for Votes by Members endpoint?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#168]
Would it be possible to include the sponsor_id in the bills node for the following endpoint?

https://api.propublica.org/congress/v1/members/K000388/votes.json

Currently have to reach out to the Bills endpoint to pull in the Sponsor ID, per vote, which is significantly slowing that page down.

These are the only Bill details currently present:
```
"votes": [
           {
           "bill": {
             "bill_id": "s114-115",
             "number": "S 114",
             "bill_uri": "https://api.propublica.org/congress/v1/115/bills/s114.json",
             "title": "To authorize appropriations and to appropriate amounts for the Veterans Choice Program of the Department of Veterans Affairs, to improve hiring authorities of the Department, to authorize major medical facility leases, and for other purposes.",
             "latest_action": "Became Public Law No: 115-46."
           }
```

I can demonstrate how that page was working with Sunlight if it would help.

**Comment by dwillis** [comment]
We've added `sponsor_id` to the votes responses - this should be live shortly.

**Comment by mininternet** [comment]
Excellent! I see it now, works just fine.

Thanks again!

**Comment by mininternet** [comment]
Oh, and just an FYI, but it appears the documentation is still not up to date with this addition - 

https://projects.propublica.org/api-docs/congress-api/members/#get-a-specific-members-vote-positions
