### ISSUE TITLE
Email address in JSON response of Members endpoint

### ISSUE THREAD

**Issue by KristieDC** [propublica/congress-api-docs#169]
Email address was provided in the previous sunlight version of the API which allowed constituents to easily contact members.

**Comment by dwillis** [comment]
Those email addresses were provided by OpenCongress, which no longer exists. Members of Congress provide contact forms, not email addresses, so we provide contact form URLs where we have them, but the API does not have email addresses.

**Comment by KristieDC** [comment]
thank you @dwillis - sadly, this was a key component of the ERA Coalition website.  Onward...
