### ISSUE TITLE
Bills Titles

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#172]
Some bills titles, like S. Res. 301 has backslashes in the name, (\National Chemistry Week\).  Could those backslashes be removed?  From https://api.propublica.org/congress/v1/115/both/bills/updated.json

**Comment by dwillis** [comment]
Hey @epanchenko - the reason for that is that they are escaping interior quote-marks in the data, so I guess one option is to convert those into single-quotes.

**Comment by epanchenko** [comment]
Ok i will replace in my code.
