### ISSUE TITLE
"Couldn't find Amendment with 'id'=" error when retrieving specific roll call votes

### ISSUE THREAD

**Issue by mkingmrss** [propublica/congress-api-docs#173]
When retrieving certain roll call votes, an error is returned with an incomplete error message. For example, submitting a request to https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/242.json returns:

```
{
    "status": "ERROR",
    "copyright": "Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
    "errors": [
        {
            "error": "Couldn&#39;t find Amendment with &#39;id&#39;="
        }
    ]
}
```

This same error is returned for roll call votes with the following IDs: 239, 240, 241, and 244.

By comparison, https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/243.json returns the expected roll call vote data.

**Comment by dwillis** [comment]
@mkingmrss thanks - this is fixed now.

**Comment by mkingmrss** [comment]
@dwillis thanks for the quick response. confirming this is fixed on my end as well.
