### ISSUE TITLE
Votes per Bill?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#174]
I don't see the ability to pull votes per bill anywhere, as with Sunlight. 

Is this perhaps a feature on the roadmap somewhere?

**Comment by dwillis** [comment]
@mininternet: each bill response has a `votes` attribute, as described at https://projects.propublica.org/api-docs/congress-api/bills/#get-a-specific-bill

**Comment by mininternet** [comment]
Ah, i see it now. 

I'd been looking in the Vote Endpoints documentation.

Thanks!
