### ISSUE TITLE
Active member flag

### ISSUE THREAD

**Issue by rootraid** [propublica/congress-api-docs#175]
Is there any way to know whether a member of congress is suddenly no longer a member of congress? for example: Tim Murphy R-Pa suddenly quit but nothin on the API [that I could find :)] notes this action.

I'm using: https://api.propublica.org/congress/v1/115/Senate/members.json

thanks

**Comment by dwillis** [comment]
Hi @rootraid: Murphy was a member of the House, while the URL you're using is for the Senate, so he wouldn't show up there. Try https://api.propublica.org/congress/v1/115/house/members.json and you'll see that Murphy is there and his resignation date is recorded. There's also an `in_office` boolean value.

**Comment by rootraid** [comment]
Thanks, my mistake typing the URL, I do use "house" for representatives and "senate" for senators. 

Using in_office is fine, I guess I am looking for something more detailed like when someone quits or any other irregular circumstance. Is there anything like that anywhere else?

**Comment by dwillis** [comment]
We do have a Members Leaving Office API call: https://projects.propublica.org/api-docs/congress-api/members/#get-members-leaving-office

**Comment by rootraid** [comment]
Thanks! Thats much closer to what Im looking for. Do you know if a member quits or dies, would                 "status" or "note"

**Comment by rootraid** [comment]
That works perfectly, thanks!
