### ISSUE TITLE
https://api.propublica.org/congress/v1/members/{member-id}/bills/{type}.json returning 500 error

### ISSUE THREAD

**Issue by primetarget** [propublica/congress-api-docs#176]
Some calls to https://api.propublica.org/congress/v1/members/{member-id}/bills/{type}.json return 500 errors.  As an example:

https://api.propublica.org/congress/v1/members/W000806/bills/introduced.json

Most calls return as expected.

**Comment by dwillis** [comment]
@primetarget - thanks for the report. This is fixed now.
