### ISSUE TITLE
Last_vote attribute in Bills JSON endpoint?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#177]
Previously with Sunlight there was a **last_vote** attribute, which was very useful for determining whether to show a Votes button in the UI.

Without a flag now the Votes button will always be displayed, which isn't useful since most bills haven't been voted on, which makes the UI misleading.

Not sure what better way to know when to offer a Votes option, per Bill.

**Comment by dwillis** [comment]
@mininternet: Individual bill responses have a `votes` attribute that, if not empty, contains a list of votes on that bill, in reverse chronological order (see https://projects.propublica.org/api-docs/congress-api/bills/#get-a-specific-bill). Does that help, or were you looking for something else?

**Comment by mininternet** [comment]
@dwillis - Would this be the case for every Bill endpoint, i.e. bills by legislator, bills by subject/search, etc?

Checking for a zero length votes array would work well, but i know there are occasional differences in field structures between endpoints, so not sure if Votes are present everywhere.

**Comment by dwillis** [comment]
@mininternet currently it's only on the Specific Bill endpoint, so no. Sounds like a `last_vote` attribute or a `has_votes` boolean would be useful on all bill endpoints? Which would be preferable?

**Comment by mininternet** [comment]
@dwillis - With Sunlight it was a last_vote date value, which provided more info than just a boolean. But if this is problematic, a boolean would work well too.

**Comment by dwillis** [comment]
@mininternet it's not problematic. We'll add it to bill responses.

**Comment by mininternet** [comment]
Excellent, thanks!

**Comment by dwillis** [comment]
@mininternet We've added `last_vote` to bill responses and generally brought more of the bill responses in line with the bill lists responses.

**Comment by mininternet** [comment]
@dwillis - Great news, thanks!

I've had a couple of fires to put out, so haven't yet implemented, but will do so by this weekend. Feel free to close this comment.
