### ISSUE TITLE
Rep. Zinke's position missing in 2017 House Roll Call 21

### ISSUE THREAD

**Issue by hhubik** [propublica/congress-api-docs#179]
The position on 2017 House roll call vote 21 of rep. Zinke (MT-At Large) is missing in the data I get from
`https://api.propublica.org/congress/v1/115/house/sessions/1/votes/21.json`

According to
[http://clerk.house.gov/evs/2017/roll021.xml](http://clerk.house.gov/evs/2017/roll021.xml)
Zinke voted Yes.

Besides Zinke's, there might be some other members' positions missing as well because I am getting only 427 positions total from the API for this vote.  I get over 430 for other votes such as rc 20.

**Comment by dwillis** [comment]
Thanks, @hhubik - this should be fixed now.
