### ISSUE TITLE
Get recent bills by enacted or vetoed

### ISSUE THREAD

**Issue by pll33** [propublica/congress-api-docs#18]
Proposing to add a bill type `enacted` and `vetoed` for [Get Recent Bills](https://propublica.github.io/congress-api-docs/#get-recent-bills). 

If there's a chamber `all`, you could possibly add another type `passed` to indicate recent bills that have passed both chambers.

I currently use a filter with the Sunlight API to [get bills the president has recently signed into law](https://congress.api.sunlightfoundation.com/bills?congress=115&history.enacted=true).

**Comment by dwillis** [comment]
We'll add enacted and vetoed to the chamber-specific responses. Let me think about having an `all` chamber parameter. Maybe `both` is better?

**Comment by pll33** [comment]
`both` works! That probably makes more sense

**Comment by dwillis** [comment]
This is now in the API: https://projects.propublica.org/api-docs/congress-api/endpoints/#get-recent-bills
