### ISSUE TITLE
Inconsistent reporting of At Large districts for 115th Congress

### ISSUE THREAD

**Issue by hhubik** [propublica/congress-api-docs#181]
The congressional district data for rep. Peter Welch (VT) reported by this URL
https://api.propublica.org/congress/v1/members/G000584.json 
is as follows:
```
"district": "1", 
"at_large": true,
```
This seems inconsistent with the district data for rep. Greg Gianforte (MT) reported by this URL
https://api.propublica.org/congress/v1/members/G000584.json:
```
"district": "At-Large", 
"at_large": false,
```
Finally, both VT and MT are inconsistent with data for rep. Don Young (AK) reported by this URL
https://api.propublica.org/congress/v1/members/Y000033.json:
```
"district": "At-Large",
"at_large": true,
```
According to [http://clerk.house.gov/member_info/olmbr.aspx](http://clerk.house.gov/member_info/olmbr.aspx), the name of all these districts is `At Large`. I propose that you report all of these as shown above for AK.  One way or another, the district reporting should be the same for all **seven** `At Large` districts listed at  [http://clerk.house.gov/member_info/olmbr.aspx](http://clerk.house.gov/member_info/olmbr.aspx).

**Comment by dwillis** [comment]
Thanks, @hhubik. We'll get this fixed.

**Comment by dwillis** [comment]
@hhubik This is fixed now.
