### ISSUE TITLE
Selecting a state on a bills page redirects to a statement page

### ISSUE THREAD

**Issue by chrislkeller** [propublica/congress-api-docs#182]
URL: https://projects.propublica.org/represent/votes/115/house/1/256

Steps to recreate: 
- Choose a state from the state dropdown beneath the Complete Roll Call section
- Data briefly filters before redirecting to https://projects.propublica.org/represent/statements?by_state=AL

Occurs in Chrome, Firefox and Safari

**Comment by dwillis** [comment]
Thanks, @chrislkeller  - this is fixed now.
