### ISSUE TITLE
Missing "Office" Data for 2 Senators

### ISSUE THREAD

**Issue by mikeshyavitz** [propublica/congress-api-docs#183]
Senator Whitehouse and Senator Sanders have no office address. According to their websites, this is the correct info: 

Sanders: 332 Dirksen Building
Whitehouse: Hart Senate Office Bldg., Rm. 530

**Comment by dwillis** [comment]
Thanks @mikeshyavitz - we'll get those in the API.

**Comment by dwillis** [comment]
This is done now.

**Comment by mikeshyavitz** [comment]
Excellent! Confirmed it's working on our end as well. Thanks.
