### ISSUE TITLE
'Journal' Vote responses?

### ISSUE THREAD

**Issue by mininternet** [propublica/congress-api-docs#184]
What is a Journal vote response? I'm seeing those come through, without sponsors, titles, etc., yet with affirmative/negative vote values. 

Should these be handled differently than Bill votes? (Apologies if overlooked in documentation)

**Comment by dwillis** [comment]
@mininternet Journal votes always have the same question: on approval of the previous legislative day's journal. They have no sponsor or title, and no real legislative significance. Often they are used to help leadership know which members are available to vote and as opportunities to whip on bills.

**Comment by mininternet** [comment]
I see. So is there any way to filter these out from the endpoint?

**Comment by dwillis** [comment]
You can filter them out on your end - they have consistent vote question `On Approving the Journal` - but we won't be removing them from the endpoint, which shows all roll call votes.

**Comment by mininternet** [comment]
I should have worded that better - I meant filter as a param in the request, not from the endpoint.

**Comment by dwillis** [comment]
No, we don't support param filters like Sunlight did. I'm also unclear why we'd isolate just these votes, as there are others that are unrelated to bills.

**Comment by mininternet** [comment]
For performance mainly. For data visualization of a Legislator's vote positions, related to Bills, I have to perform multiple requests to the API. The non Bill related votes data makes each request larger, plus requires additional client side overhead.

Not sure how much more performant pulling only a Legislator's bill votes would be, so this may just be an edge case. Thanks for the explanation. Feel free to close this out.

**Comment by dwillis** [comment]
Most votes in the House are on bills, so I'm not sure it would make a huge difference.
