### ISSUE TITLE
Invalid JSON in Recent Votes response

### ISSUE THREAD

**Issue by njgingrich** [propublica/congress-api-docs#186]
Visiting https://api.propublica.org/congress/v1/senate/votes/recent.json the response I get back is not valid JSON. In particular, this section:

`
{
				"congress": 115,
				"chamber": "Senate",
				"session": 2,
				"roll_call": 2,
				"source": "https://www.senate.gov/legislative/LIS/roll_call_votes/vote1152/vote_115_2_00002.xml",
				"url": "https://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?congress=115&session=2&vote=00002",
				"vote_uri": "https://api.propublica.org/congress/v1/115/senate/sessions/2/votes/2.json",
				"bill": {},
				"amendment": {},
				"nomination": {
					"nomination_id": "PN748-115",
					"number": "PN748",
					"name": "William L. Campbell Jr.",
					"agency": "The Judiciary"
				},
				"question": "On the Cloture Motion",
				"description": "William L. Campbell, Jr., of Tennessee, to be United States District Judge for the Middle District of Tennessee",
				"vote_type": "1/2",
				"date": "2018-01-08",
				"time": "17:32:00",
				"result": "Cloture Motion Agreed to",
				"tie_breaker": "",
				"tie_breaker_vote": "",
				"document_number": "748",
				"document_title": "William L. Campbell, Jr., of Tennessee, to be United States District Judge for the Middle District of Tennessee",
				"democratic": {
					"yes": ,
					"no": ,
					"present": ,
					"not_voting": ,
					"majority_position": ""
				},
				"republican": {
					"yes": ,
					"no": ,
					"present": ,
					"not_voting": ,
					"majority_position": ""
				},
				"independent": {
					"yes": ,
					"no": ,
					"present": ,
					"not_voting":
				},
				"total": {
					"yes": 89,
					"no": 1,
					"present": 0,
					"not_voting": 10
				}
			},
`
Where one can see that the different positions, `democratic`, `republican`, and `independent` do not have any values passed for `yes`, `no`, `present`, and `not_voting`.

**Comment by njgingrich** [comment]
Here's the senate.gov page for the vote: https://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?congress=115&session=2&vote=00002

**Comment by dwillis** [comment]
@njgingrich Sorry about that - this should be fixed now.

**Comment by njgingrich** [comment]
Thank you so much!
