### ISSUE TITLE
Enhancement: Include New Lines and Spacing in Bill Summary

### ISSUE THREAD

**Issue by jden1705** [propublica/congress-api-docs#187]
When using the Bill Summary from the specific bill call the text is all in one line which can make it difficult to read as intended. Would it be possible to include at least new line breaks in the summary/short summary fields if not other formatting which might be applied? (or in a new formatted one)

**Comment by dwillis** [comment]
Hi @jden1705. The bill summaries as published by GPO include HTML tags, but we strip them out currently. It seems to me that there are a couple of options if we wanted to change things: 

1. Reproduce the HTML entities (which include bold and paragraph tags).
2. Replace them with JSON-escaped newlines.

I'm not crazy about the first, but open to discussion.

**Comment by jden1705** [comment]
For my personal use all I really need is the new line breaks per option 2 to add some readability, and if this isnt something a lot of people are looking for then i don't see the need to go full out with option 1.
