### ISSUE TITLE
Committees and Bills not returning for specific members in XML

### ISSUE THREAD

**Issue by johnalexhall85** [propublica/congress-api-docs#190]
When I hit the specific member endpoint to return XML, the committee and sponsored bill information for the member is missing. It returns correctly with JSON, but not XML. Has returning XML been deprecated in the Congress API?

**Comment by dwillis** [comment]
Hi @johnalexhall85 - XML responses have NOT been deprecated. Can you give me specific urls that aren't working for you?

**Comment by johnalexhall85** [comment]
https://api.propublica.org/congress/v1/members/A000360.xml

I've tried others too including *P000612.xml

**Comment by johnalexhall85** [comment]
They work. I get all of the other information, just not committees and bills.

**Comment by dwillis** [comment]
I see what you mean for committees - we'll add those. Member bill responses are a separate thing: https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills-by-a-specific-member

**Comment by johnalexhall85** [comment]
Ah, gotcha. Thanks!

**Comment by dwillis** [comment]
Ok, committees should be there now.
