### ISSUE TITLE
question re: bill date availability

### ISSUE THREAD

**Issue by knickfan** [propublica/congress-api-docs#192]
I am running some calls for bill votes by date (year and month) and not knowing what years/months are available, I ran for both houses from January 1980 to February 2018.  A few questions/items of note:

- what is the correct start month/year for bill votes for each chamber?
- see attached spreadsheet for 4 instances returning 500 error code
- see attached spreadsheet for more than 20 instances throwing JSONDecodeError
- there are many cases of calls returning no bill votes but I'll assume there really is no data

Attached spreadsheet contains all results with anomalies highlighted.

Thanks

[billvotes.xls.zip](https://github.com/propublica/congress-api-docs/files/1693599/billvotes.xls.zip)

**Comment by dwillis** [comment]
Thanks, @knickfan. The docs [say this](https://projects.propublica.org/api-docs/congress-api/#overview) about vote data: "Votes are available from 1991 for the House of Representatives and from 1989 for the Senate."

I'll check out the errors in the spreadsheet and get them fixed, and most bills don't get voted on.

**Comment by dwillis** [comment]
An update: turns out these are almost all Quorum call votes & should be fixed today.

**Comment by dwillis** [comment]
These urls now work properly. Thanks for the report!

**Comment by knickfan** [comment]
Ran for both chambers across all years and everything works as expected.
