### ISSUE TITLE
Update current committee membership information

### ISSUE THREAD

**Issue by justinvasel** [propublica/congress-api-docs#193]
My apologies if this is not the right venue for this sort of request.

There is outdated committee membership information for the 115th congress. I believe this data comes from the folks at https://github.com/unitedstates/congress-legislators. They just updated this information, and I've verified that some of the inconsistencies I observed are now corrected on their end.

I did not see committee membership information listed in the data update schedule in your docs, so I wan't sure if it needed to be requested manually.

If it is not automatic, could someone pull this updated data in?

**Comment by dwillis** [comment]
Hi @justinvasel - thanks. We do use the unitedstates project data, but also update manually at times. Can you point me to outdated membership information in the API now?

**Comment by justinvasel** [comment]
For example: https://api.propublica.org/congress/v1/115/house/committees/HSBU/
`HSBU` has Diane Black listed as chair (it is now Steve Womack) and Chris Van Hollen listed as ranking member (he is now a Senator).

Another example is `HSGO`: https://api.propublica.org/congress/v1/115/house/committees/HSBU/, which has Jason Chaffetz listed as the chair, but is not present in the `current_members` list.

**Comment by dwillis** [comment]
@justinvasel thanks; those are fixed, and we'll review the chair/rankings on other cmtes.

**Comment by justinvasel** [comment]
Great! Thanks so much for the quick response.

**Comment by justinvasel** [comment]
Hello. Do you need to check each committee by hand, or do you have an automated way of updating the membership information? I've stumbled upon a handful of other cases. I've included a screenshot of the app I'm developing which lists the committees, along the with chair and ranking member (last two columns).

![screen shot 2018-02-13 at 1 03 10 pm](https://user-images.githubusercontent.com/3528936/36165855-decc26d4-10be-11e8-8ca6-32e40743ed85.png)

From the screenshot you can see some ranking member info is missing. Those seem to be cases of members who are no longer in Congress. Also, there is one instance where the chair and ranking member are listed as the same person.

I suspect this may also apply to the subcommittee membership information, but I haven't confirmed that. If you'd like, I can try to compile a master list of those I find, but an automated solution would certainly be faster.

Sorry for any inconvenience, and thank you for your help on this issue :)

**Comment by justinvasel** [comment]
Thank you @dwillis. I really appreciate all your help :)
