### ISSUE TITLE
Invalid JSON

### ISSUE THREAD

**Issue by jschutt** [propublica/congress-api-docs#194]
Hello, I'm seeing some invalid JSON responses on the following calls:

https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/94.json
https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/125.json
https://api.propublica.org/congress/v1/115/senate/sessions/1/votes/249.json
https://api.propublica.org/congress/v1/115/house/sessions/1/votes/78.json
https://api.propublica.org/congress/v1/115/house/sessions/1/votes/202.json

Am I doing something wrong?

Thank you!

**Comment by dwillis** [comment]
@jschutt - Thanks for the report - we've fixed these.

**Comment by jschutt** [comment]
Thank you @dwillis - Much appreciated
