### ISSUE TITLE
Document endpoint syntax for getting at-large members by district.

### ISSUE THREAD

**Issue by scottb** [propublica/congress-api-docs#196]
Member `N000147` is an at-large representative for DC in the house. Attempting to query the current members for the house appears to require both state and district, but offers no guidance on what to pass as the district for at-large representatives.

I've tried `At-Large`, `0`, and `1`, and I've tried just passing the state, with no district. They all give empty responses. How can I indicate an at-large rep?

**Comment by dwillis** [comment]
@scottb You're right; we'll clarify. In the meantime, https://api.propublica.org/congress/v1/members/house/DC/current.json will work.

**Comment by scottb** [comment]
I thought I tried that but apparently I used the wrong chamber. That syntax does work. Thanks.

**Comment by dwillis** [comment]
@scottb We've added some clarification to the docs; you can use the above url form or specify a `district` of 1 for states with at-large members, plus territories, D.C. and Puerto Rico. https://projects.propublica.org/api-docs/congress-api/members/#get-current-members-by-statedistrict
