### ISSUE TITLE
Getting a CAPTCHA Check When Loading a Legislator, Committee

### ISSUE THREAD

**Issue by mikeshyavitz** [propublica/congress-api-docs#197]
It's only happening on some records, for example this one legislator B001245: Delegate Madeleine Bordallo of Guam. Here's the API call: 

https://api.propublica.org/congress/v1/members/B001245.json

I get the following output:

![image](https://user-images.githubusercontent.com/4268287/36322343-f5d5a5ae-131a-11e8-906b-7d303babd7ea.png)

Any ideas what could be causing this?

**Comment by dwillis** [comment]
@mikeshyavitz Ugh, yes, that's on our end. We're on it.

**Comment by dwillis** [comment]
@mikeshyavitz Should be fixed now.

**Comment by mikeshyavitz** [comment]
Looks like everything is working again. Thanks!
