### ISSUE TITLE
JSON for hearings endpoint is invalid

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#200]
There's a JSON parse error when consuming the hearings endpoint at:

https://api.propublica.org/congress/v1/115/committees/hearings.json?offset=0

In Python:

```
JSONDecodeError: Expecting value: line 270 column 14 (char 14014)
```

Looks like near the end of the file, there's an additional comma before the end of the array:

```
                 "bill_ids": [],
                 "url": "http://docs.house.gov/Committee/Calendar/ByEvent.aspx?EventID=108000",
                 "meeting_type": "Hearing"
               },
             ]
      }
   ]
}
```

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
Confirmed! Thank you.

**Comment by konklone** [comment]
Hearings are causing crashes again. I haven't tracked down the exact cause of it again, but it seems likely it's a recurrence of the same error. I can post more details later from a computer where I have API access.

**Comment by dwillis** [comment]
Yep, looks like it. Will fix.

**Comment by dwillis** [comment]
Check now.

**Comment by konklone** [comment]
Working again! Thanks for the quick fix.
