### ISSUE TITLE
Position of Mike Capuano (MA-7) missing from 2017 House votes 560 and 561

### ISSUE THREAD

**Issue by hhubik** [propublica/congress-api-docs#203]
I checked the data for vote 559 and 570, and Capuano is in both of those. Don't know if he is missing from some other votes besides 560 and 561.

**Comment by hhubik** [comment]
Capuano is also missing from votes 562 and 563.  He is in 564 and 565.

**Comment by dwillis** [comment]
@hhubik Thanks - not sure why this happened but data for roll calls 560, 561, 562 and 564 have been reloaded and Capuano is in there now.
