### ISSUE TITLE
Missing Twitter accounts from Senators

### ISSUE THREAD

**Issue by nbs** [propublica/congress-api-docs#204]
Amy Klobuchar
https://twitter.com/amyklobuchar

I'm guessing hers is missing because the website linked from the account is her personal one and not her office, but I would argue it is an active account from which she posts things related to her position.

Rand Paul
https://twitter.com/RandPaul

This one does link to his official site, so I'm not sure why this one is missing.

Can these be added to the API?

Thanks

**Comment by dwillis** [comment]
@nbs You are correct as to why those accounts are not included in the API. We adopt the approach taken by the [United States project](https://github.com/unitedstates/congress-legislators#data-on-official-social-media-accounts) that we source some of our data from. The Klobuchar account is clearly a political one - it links to her campaign site. The Rand Paul account is a judgment call - it does link to his official site but it also has long been used as a personal account.

**Comment by nbs** [comment]
Thanks for your response.

I understand your reasoning but just wanted to throw our use case out there for consideration.

We're using the Twitter accounts as a way of letting people contact their representatives and their staffers about a political issue that is important to them. Those accounts, official or not, are legitimate ways of contacting that representative through Twitter.

We were hoping to rely on the API to provide us complete data for this purpose, and it'd be ideal to not to have to implement fallbacks for certain representatives.
