### ISSUE TITLE
Some bill endpoints do not return well-formed JSON

### ISSUE THREAD

**Issue by tillahoffmann** [propublica/congress-api-docs#206]
The following endpoints does not return well-formed JSON (generated by some debug code):
```
Invalid JSON for 'https://api.propublica.org/congress/v1/105/bills/hr4328.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr3018.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr3439.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/s777.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr4444.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/s1402.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr3544.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr4205.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/106/bills/hr2932.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hr1368.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hr2309.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hconres328.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hr2844.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hr1587.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hres713.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/hr2028.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/108/bills/s878.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hres91.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hres195.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hres228.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hr458.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hconres191.json'
Invalid JSON for 'https://api.propublica.org/congress/v1/109/bills/hr739.json'
```

It looks like the problems may be a result of some special characters in the description of the bill not being escaped properly.

**Comment by dwillis** [comment]
@tillahoffmann thanks - we're on it. just out of curiosity, are you grabbing every bill from the API?

**Comment by dwillis** [comment]
These are fixed now.

**Comment by tillahoffmann** [comment]
Thank you for the fixes! I've been going over large numbers of bills algorithmically to determine when the House and the Senate voted on the same bill text, i.e. passage/rejection of the bill in both chambers before presentation to the President. However, I can't quite extract the data I'm looking for.

For example, [this bill](https://www.congress.gov/bill/104th-congress/senate-bill/4) has been enacted but the response from `https://api.propublica.org/congress/v1/104/bills/s4.json` does not provide `house_passage` information. Is that a result of differences being resolved in conference committee?

**Comment by dwillis** [comment]
No, it's because there was no roll call vote on that bill in the House. To be honest, I'm not sure that our API is the best way to go about answering your question, only because we don't include bill versions in the data (yet). Each bill can have multiple versions, and GPO has published bill version text for the 113th-115h congresses, but not before then (although you can see versions on congress.gov).

**Comment by tillahoffmann** [comment]
Thank you for the update! Do you think accessing the bill status using the bulk data access (https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md) would be more appropriate for my purposes?

**Comment by dwillis** [comment]
Yes, although that only covers the 113th, 114th and 115th congresses.
