### ISSUE TITLE
Missing govtrack ID's

### ISSUE THREAD

**Issue by CmdrAdama** [propublica/congress-api-docs#208]
The following members have missing gov track ID's

Conor Lamb
id: L000588
govtrack_id: 412744 
https://www.govtrack.us/congress/members/conor_lamb/412744

Beto O’Rourke
id: O000170
govtrack_id: 412575
https://www.govtrack.us/congress/members/beto_orourke/412575

Debbie Lesko
id: L000589
govtrack_id: 412745
https://www.govtrack.us/congress/members/debbie_lesko/412745

Cindy Hyde-Smith
id: H001079
govtrack_id: 412743
https://www.govtrack.us/congress/members/cindy_hyde_smith/412743

**Comment by dwillis** [comment]
These members have their `govtrack_id` values populated now.
