### ISSUE TITLE
Pagination for committee hearings

### ISSUE THREAD

**Issue by crawfoal** [propublica/congress-api-docs#209]
We are testing the [recent committee hearings](https://projects.propublica.org/api-docs/congress-api/committees/#get-recent-committee-hearings) endpoint and ran into some issues.

  1. The example call given in the docs looks like this:
      ```
        curl "https://api.propublica.org/congress/v1/115/committees/hearings.json"
           -H "X-API-Key: PROPUBLICA_API_KEY"
      ```
      This does not appear to respond to an `offset` query string parameter. It might only return senate hearings, but without pagination we can't be sure.

  2. When we add a chamber (e.g. `https://api.propublica.org/congress/v1/115/house/committees/hearings.json`) the pagination via `offset` **does** work. The results we get in this case start about a month or two back though, they are no longer *just* upcoming events - this is fine, but I just wanted to note it because it is weird behavior.

It would be helpful to mention exactly how to use the query string parameter, and that it is currently only working for chamber specific endpoints.

**Comment by crawfoal** [comment]
I looked into this more, and I think when we add a chamber in there we only get past events, whereas without that we get upcoming ones (but again only 20).

**Comment by dwillis** [comment]
@crawfoal thanks - we've fixed the recent committee hearings endpoint so it now supports the offset parameter. You've identified another problem with the House hearings loader that we're fixing.

**Comment by dwillis** [comment]
@crawfoal the House hearings loader has been fixed and should give you current (and future) hearings now.
