### ISSUE TITLE
Internal Server Error 500 for House of Representatives member votes

### ISSUE THREAD

**Issue by pll33** [propublica/congress-api-docs#21]
https://api.propublica.org/congress/v1/members/{member-id}/votes.json

Tried looking up a few House of Representatives [members' vote positions](https://propublica.github.io/congress-api-docs/#get-a-specific-member-39-s-vote-positions) today and kept getting 500 errors. 

Senate members vote positions seems to be working just fine though.

**Comment by dwillis** [comment]
Thanks, @pll33, this is fixed now.
