### ISSUE TITLE
Statements about subjects missing some members

### ISSUE THREAD

**Issue by JackPloshnick** [propublica/congress-api-docs#211]
I have been making use of the Congressional Statements tool (its amazing thanks so much!) and I noticed that it does not contain any statements made by Chuck Schumer. Specifically, the statement by subject request returns no Chuck Schumer results. Can this issue be addressed? Thanks!

**Comment by dwillis** [comment]
Hi @JackPloshnick - Can you tell me what request you're using? Because [this one](https://api.propublica.org/congress/v1/members/S000148/statements/115.json) returns recent statements by Schumer.

**Comment by JackPloshnick** [comment]
hi @dwillis- the api call I have been making is:
"https://api.propublica.org/congress/v1/statements/subject/affordable-care-act-repeal.json?query&offset=0" with the offset ranging from 0:2260. 

For whatever reason, no Schumer.

Two additional minor things i've noticed:
The links to the statements by Rand Paul do not work.
Beto O'Rourke is listed as a senator. 

Thanks!

**Comment by dwillis** [comment]
@JackPloshnick thanks. A couple of things that we should add to the docs, but the important one is that these subjects aren't automatically assigned, so they may miss some statements. I'll check back on the ACA subject, but I'd recommend using the search endpoint to ensure you get everything about a certain phrase or keyword.

On Rand Paul - he changed his site, so some older statements won't resolve. There's not a lot we can do about that if offices don't set up redirects, but I'll take a look. And I'll fix O'Rourke's statement data - he's running for the Senate, but is still in the House.

**Comment by dwillis** [comment]
We've added some additional documentation to the statements by subject response to clarify that these are not automatically assigned and may not be comprehensive. O'Rourke's chamber is now fixed, too.

**Comment by JackPloshnick** [comment]
Awesome thanks for fixing this. Will the Schumer data eventually be added to the ACA subject or should I get his press releases another way?

**Comment by dwillis** [comment]
I might just pull his releases and filter on titles or use the search endpoint to make sure you have his.

**Comment by JackPloshnick** [comment]
Sounds great, will do. Another thing I noticed btw, on the same ACA call, Paul Ryan is listed as a senator. This API is a life-saver! Thanks so much for putting so much work into it.

**Comment by dwillis** [comment]
Oh, good catch. I know what's causing that and will fix.
