### ISSUE TITLE
where can I find from and to dates for Senate "Congress Numbers"?

### ISSUE THREAD

**Issue by knickfan** [propublica/congress-api-docs#213]
I'm looking for the from and to dates for CongressNo as found in the members API.  This is simple for the house but unable to find for the senate. Any ideas?

Also, how/where are the FEC IDs coming from? Some of them are wrong in that FEC ID for house starts with "H", senate starts with "S", and president starts with "P".  In the congress API Senator McCain's FEC ID is the one from his presidential run P80002801 but should be S6AZ00019.

**Comment by dwillis** [comment]
@knickfan The start and end dates are the same for House and Senate for congresses covered by the API - generally they run from January 3 of the odd-numbered year (2017, for example) to Jan. 3 two years after (2019). The FEC IDs come from the FEC, and individuals can have more than one FEC ID over time. McCain's API response has his Senate ID for the 115th Congress, for example, and we'll update his 114th Congress record with that ID.
