### ISSUE TITLE
Parse error: Get Votes by (range) Date 

### ISSUE THREAD

**Issue by DavytJ** [propublica/congress-api-docs#216]
In: https://api.propublica.org/congress/v1/{chamber}/votes/{start-date}/{end-date}.json
Example: "https://api.propublica.org/congress/v1/both/votes/2017-01-03/2017-01-31.json"
Return an error for the content
Error: parse error: invalid object key (must be a string)
          2,"Lewis (GA)":1},           },         {            "congre
                     (right here) ------^
If I not require the content return:
Response [https://api.propublica.org/congress/v1/house/votes/2017-01-03/2017-01-31.json]
  Date: 2018-10-27 22:54
  Status: 200
  Content-Type: application/json; charset=utf-8
  Size: 131 kB
{
   "status":"OK",
   "copyright":"Copyright (c) 2018 Pro Publica Inc. All Rights Reserved.",
   "results": {
      "chamber": "House",
      
      "start_date": "2017-01-03",
      "end_date": "2017-01-31",
      "num_results": 69,
      "votes": [

**Comment by dwillis** [comment]
@DavytJ thanks - I'm pretty sure this is an issue with votes for Speaker of the House, which means it should be isolated to House votes in January of odd-numbered years. We'll fix it.

**Comment by dwillis** [comment]
This is fixed now.

**Comment by DavytJ** [comment]
Yes! It's fixed
