### ISSUE TITLE
Vote API not returning full question text

### ISSUE THREAD

**Issue by BananaNeil** [propublica/congress-api-docs#218]
Hey folks, I'm migrating over from sunlight's data, and I'm noticing that the `question` field is cut off for senate votes, in comparison to what sunlight returned. 

For senate votes, it seems that the Propublica `question` is equivalent to the Sunlight's `roll_type`, and Sunlight's `question` is not being returned at all.

I checked on the source xml files, and the full question is present under the key `vote_question_text`:
https://www.senate.gov/legislative/LIS/roll_call_votes/vote1152/vote_115_2_00106.xml
And this seems to be the case for all senate votes. 

I have several use cases that require the full vote question, and I was hoping that could be added as an additional key to the responses.

**Comment by dwillis** [comment]
@BananaNeil Thanks for this. We'll see if we can't add it soon.

**Comment by dwillis** [comment]
@BananaNeil We're updating the data to return the vote question

**Comment by dwillis** [comment]
We've added `question_text` to vote responses (although it only will have values for Senate votes).
