### ISSUE TITLE
Endpoint or Way to Programatically Get the Current Congress Integer Value

### ISSUE THREAD

**Issue by stateisbad** [propublica/congress-api-docs#219]
Sorry if this is spelled out somewhere, but I'm trying to find a way using this API to get the current congress' numerical value (i.e. 115) in a programmatic way. Once obtained, I can then use that value to query other endpoints that require it. As of now, I'm explicitly setting it to the current numerical value, but every two years I would need to update that.

Any guidance would be appreciated. Thanks!

**Comment by dwillis** [comment]
@br00tal You're right, each new congress increments by one, so the congress beginning on Jan. 3, 2019 would be the 116th. Probably could set this in code with some logic. Here's a ruby method for deriving the congress from a given year:

```
def self.congress_for_year(year)
    ((year.to_i + 1) / 2) - 894
end
```

**Comment by stateisbad** [comment]
Oh, nice, I didn't even think of that. That would probably work nicely. I'll give that a shot.
