### ISSUE TITLE
Bills endpoints do not specify committee code along side committee name

### ISSUE THREAD

**Issue by briangsweeney** [propublica/congress-api-docs#22]
Bills endpoints documented [here](https://propublica.github.io/congress-api-docs/#bills) cite a committee but do not give a committee code, as found when querying for specific [members](https://propublica.github.io/congress-api-docs/#members).  This is an issue because the names of committees returned from Bills endpoints do not come in the same format as results derived from the Members or Committees endpoints.  For example, a get specific bill request might show a committee as 'House Agriculture Committee' while a specific member request might show that same committee as 'Committee On Agriculture' with 'House' being specified in a separate field.

To reproduce:
1 Run request: https://api.propublica.org/congress/v1/115/house/bills/introduced.json
2 Run request: https://api.propublica.org/congress/v1/115/house/committees/HSAG.json
3 Note that committee appears to be the same entity but the verbiage differs.
4 Observe that both requests are lacking a code which could have been used to disambiguate these two entities.  (Requests for members present such a code.)

**Comment by dwillis** [comment]
@briangsweeney we've added committee codes to the bill list responses (like https://api.propublica.org/congress/v1/115/house/bills/introduced.json).

**Comment by jden1705** [comment]
Noticed this is implemented as a list of committee codes. Can a bill be a part of more than one committee? Can you point me to an example bill?

And in that case would the committees field also return a list?

**Comment by dwillis** [comment]
@jden1705 A bill can be referred to multiple committees, yes (here's an example: https://api.propublica.org/congress/v1/115/bills/hr2131.json). We'll be working to change the committees attribute, but that's a breaking change so we didn't do it as quickly as we could add a new attribute.

**Comment by jden1705** [comment]
Interesting. Thanks!

**Comment by briangsweeney** [comment]
@jden1705 but there is committees endpoint which takes the code as it's argument so you could figure out the human readable name by using the committee codes.  see above.
