### ISSUE TITLE
H.R.7319 is the same as H.R.7318

### ISSUE THREAD

**Issue by slugiscool99** [propublica/congress-api-docs#221]
The propublica congress api returns the same information for hr7319 and hr7318

They're different on congress.gov

https://www.congress.gov/bill/115th-congress/house-bill/7318
https://www.congress.gov/bill/115th-congress/house-bill/3719

However they are the same on govtrack.us
https://www.govtrack.us/congress/bills/115/hr7319
https://www.govtrack.us/congress/bills/115/hr7318

Maybe this is what's causing the issue?

**Comment by dwillis** [comment]
@slugiscool99 I don't think that is true. Just looked at both bills, and while _similar_, they have different titles, different summaries and other small differences. They are not identical on congress.gov, govtrack.us or the API.
