### ISSUE TITLE
Subcommittee endpoints for 116th Congress returns HTTP status 500

### ISSUE THREAD

**Issue by justinvasel** [propublica/congress-api-docs#222]
For both houses of Congress, and only for 116th Congress, the individual subcommittee endpoints are returning:
```json
{
    "status": "500",
    "error": "Internal Server Error"
}
```

Example endpoint: https://api.propublica.org/congress/v1/116/house/committees/HSAG/subcommittees/HSAG03.json

The committee endpoints are working fine (ie. https://api.propublica.org/congress/v1/116/house/committees/HSAG.json).

Issue #124 a couple years ago details a similar (same?) issue, which was the result of a problem with the "committee hearings loader".

**Comment by dwillis** [comment]
Thanks, @justinvasel. We're in the process of updating the 116th congress committee assignments this week, and this will be fixed when we finish that.

**Comment by justinvasel** [comment]
Sorry to be a pain. Is there an expected timescale for this fix?

Thanks.

**Comment by dwillis** [comment]
We're working on it this week: https://github.com/unitedstates/congress-legislators/issues/630

Right now we have no subcommittee assignment data, so you're not missing anything by it not working at the moment, but we're on it. Some subcommittee assignments are not yet complete or published as well.

**Comment by justinvasel** [comment]
Great, thanks for the update and linking to the other issue. Much appreciated!

**Comment by dwillis** [comment]
@justinvasel this should be resolved now, but please kick the tires and let me know if you see anything odd.

**Comment by justinvasel** [comment]
Works like a charm! Thanks for you all your hard work on this, @dwillis! 🥇
