### ISSUE TITLE
"message: unauthorized" everytime

### ISSUE THREAD

**Issue by connerxyz** [propublica/congress-api-docs#223]
I get `message: unauthorized` with every request I make. Example:

```
curl "https://api.propublica.org/congress/v1/house/members.json" -H "X-API-KEY [REDACTED]"
```

**Comment by dwillis** [comment]
@connerxyz I think the request you're trying to make is https://api.propublica.org/congress/v1/116/house/members.json

For many requests you need to include the congress.
