### ISSUE TITLE
Inconsistent member State values

### ISSUE THREAD

**Issue by ndawg** [propublica/congress-api-docs#224]
In most replies, it seems that member states are represented using their two letter abbreviations, for example `TX` or `VA`. However, sometimes there are requests that return a different format. For example, [Get Amendments for a Specific Bill](https://projects.propublica.org/api-docs/congress-api/bills/#get-amendments-for-a-specific-bill) uses some weird abbreviated system, like `Tex.` and `Ohio`. It would be great to have this consistent.

**Comment by dwillis** [comment]
@ndawg Do you have an example request where this is occurring? I haven't been able to reproduce.

**Comment by ndawg** [comment]
@dwillis The [request I linked](https://projects.propublica.org/api-docs/congress-api/bills/#get-amendments-for-a-specific-bill) has an example under "Example Call" on the page.
```
            {
                "amendment_number": "S.AMDT.727",
                "slug": "samdt727",
                "sponsor_title": "Sen.",
                "sponsor": "John Cornyn",
                "sponsor_id": "C001056",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001056.json",
                "sponsor_party": "R",
                "sponsor_state": "Tex.",
                "introduced_date": "2017-07-28",
                "title": "",
                "congressdotgov_url": "https://www.congress.gov/amendment/115th-congress/senate-amendment/727/text",
                "latest_major_action_date": "2017-07-28",
                "latest_major_action": "Senate amendment submitted"
            }
```

**Comment by dwillis** [comment]
@ndawg Ok, thanks. The bill amendments requests should now return the two-character state abbreviation now, and we'll update the docs.
