### ISSUE TITLE
Missing Congressman "Office" and "Phone" Data

### ISSUE THREAD

**Issue by TLBeall** [propublica/congress-api-docs#225]
Via this request: https://api.propublica.org/congress/v1/116/house/members.json

Looks like the data is missing office information and phone numbers for 6 members:
Jenniffer Gonzalez-Colon
Eleanor Holmes Norton
Stacey Plaskett
Amata Coleman Radewagen
Gregorio Kilili Camacho
Michael San Nicolas

**Comment by dwillis** [comment]
This is fixed now.
