### ISSUE TITLE
Missing Position Data for 113th house session 2 (2014)

### ISSUE THREAD

**Issue by Nhorning** [propublica/congress-api-docs#226]
For the 113th congress, house session 2 in 2014 position data is missing for roll calls 12 - 19, 38, and 39. 

empty lists are returned.  Navigating to the relevant url reveals the data is present in the source xml.

**Comment by dwillis** [comment]
@Nhorning Thanks for this - we've loaded those positions now.

**Comment by Nhorning** [comment]
@dwillis Thanks for being so responsive!  I also noticed missing data for house session 111 (2009)
roll calls: 414, 987, 990
https://github.com/Nhorning/Congressional_Survival/blob/master/Data%20Wrangling.ipynb

**Comment by Nhorning** [comment]
It's also still missing data in house session 113 session 2. Now for calls 2 and 338. But that's quite an improvement from before!

**Comment by dwillis** [comment]
@Nhorning Thanks - these should be resolved now.
