### ISSUE TITLE
500 for cosponsored endpoint

### ISSUE THREAD

**Issue by zzolo** [propublica/congress-api-docs#23]
I am getting a `500` on the following URIs with any member ID:
`https://api.propublica.org/congress/v1/members/E000179/bills/cosponsored.json`

Body response:
```{ status: '500', error: 'Internal Server Error' }```

This has been consistent for me for the past few days at least.

**Comment by dwillis** [comment]
Sorry about that - this is fixed now.

**Comment by zzolo** [comment]
Thanks!
