### ISSUE TITLE
Pagination for New Members

### ISSUE THREAD

**Issue by zamorarr** [propublica/congress-api-docs#230]
Great API! Thanks for making this. It looks like the [New Members](https://projects.propublica.org/api-docs/congress-api/members/#get-new-members) endpoint is not respecting the `offset` parameter. It is supposed to? The following queries return the same 20 results.

```
curl "https://api.propublica.org/congress/v1/members/new.json?offset=0"
     -H "X-API-Key: PROPUBLICA_API_KEY"
```

```
curl "https://api.propublica.org/congress/v1/members/new.json?offset=20"
     -H "X-API-Key: PROPUBLICA_API_KEY"
```

There are more than 20 new members of the 116th congress though.

**Comment by dwillis** [comment]
@zamorarr Hi Robert. New members doesn't refer to all members of a new class; it only returns the most recent 20 members of Congress in reverse chronological order. You can grab all freshmen from the all House members response and filter on those with seniority of 1.

**Comment by zamorarr** [comment]
Gotcha. Thanks for the clarification!
