### ISSUE TITLE
Endpoint returns 200 instead of status

### ISSUE THREAD

**Issue by zamorarr** [propublica/congress-api-docs#231]
Hi - thanks for the great API! Currently the [Get Recent Bills by a Specific Subject](https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills-by-a-specific-subject) endpoint returns json that look like this:

```sh
curl "https://api.propublica.org/congress/v1/bills/subjects/meat.json"
  -H "X-API-Key: PROPUBLICA_API_KEY"
```

```sh
{
    "200": "OK",
    "copyright": "Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
    "num_results": 20,
    ...
}
```

These results are fine, but the use of `"200": "OK"` seems inconsistent with all other endpoints, which use `"status": "OK"` instead. Is is possible to change this to be more consistent with the other endpoints? Thanks.

**Comment by dwillis** [comment]
This is fixed now, thanks!
