### ISSUE TITLE
/:chamber/floor_updates.json has 'date' parameter in docs response, but not in actual

### ISSUE THREAD

**Issue by njgingrich** [propublica/congress-api-docs#233]
[This page](https://projects.propublica.org/api-docs/congress-api/other/#get-recent-house-and-senate-floor-actions) has `date` within its example response:

```
{
   "status":"OK",
   "copyright":" Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "congress": "115",
         "chamber": "Senate",
         "date": "2017-05-02",
         "num_results": 19,
         "offset": 0,
         "floor_actions": [...]
      }
```

But the actual response from `https://api.propublica.org/congress/v1/116/senate/floor_updates.json` does not:

```
{
  "status": "OK",
  "copyright": " Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.",
  "results": [
    {
      "congress": "116",
      "chamber": "Senate",
      "num_results": 20,
      "offset": 0,
      "floor_actions": [...]
    }
```

Also, the `congress` parameter has no effect - `https://api.propublica.org/congress/v1/116/senate/floor_updates.json` returns the same data as `https://api.propublica.org/congress/v1/6/senate/floor_updates.json`.

**Comment by dwillis** [comment]
@njgingrich thanks for this. here's what we've done:

1. Removed the date from the most recent floor updates responses.
2. URLs like `https://api.propublica.org/congress/v1/116/senate/floor_updates.json` will still work as before, with the congress parameter included, but so will URLs like `https://api.propublica.org/congress/v1/senate/floor_updates.json`, which don't show the congress parameter.

**Comment by njgingrich** [comment]
Thanks for the update!
