### ISSUE TITLE
Parameters/pagination for member vote positions

### ISSUE THREAD

**Issue by hrecht** [propublica/congress-api-docs#234]
Hello, I'm trying to get data for a member's votes back to a certain date/term, say two years, using the member votes endpoint.
https://projects.propublica.org/api-docs/congress-api/members/#get-a-specific-members-vote-positions

Is there any way to specify a range of dates or congressional terms to get data for? Or information in the response about number of pages available (maybe I'm overlooking that?) Currently the only solution I see is to make this API call with offset increasing by 20 until some limit is reached or there is no more data.

If there's no existing way to get the number of pages available or specify dates that would be a very helpful feature to add.

**Comment by dwillis** [comment]
@hrecht Yeah, you're right in that currently the only way to do this is to paginate through a member's positions. The response does offer a `total_votes` attribute, which you can divide by 20 to get the number of pages. Would that help?

**Comment by hrecht** [comment]
That would work! I'm not seeing the total_votes attribute though - which part of the response should it be in?

**Comment by hrecht** [comment]
Here's the output that I get using the example call
`curl "https://api.propublica.org/congress/v1/members/K000388/votes.json"
  -H "X-API-Key: PROPUBLICA_API_KEY"`
[temp.json.zip](https://github.com/propublica/congress-api-docs/files/3482658/temp.json.zip)

**Comment by dwillis** [comment]
Hmm, yeah. Not sure when `total_votes` got dropped, but lemme get it back.

**Comment by hrecht** [comment]
Thanks Derek! While you're adding that - it would be great to have a similar record of total responses available, like `total_bills` for the recent bills endpoint (https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills).

**Comment by dwillis** [comment]
@hrecht I think we can add that, but if you're looking for bulk data on bills, we've got something for that already that might make it easier for you to deal with programmatically:

https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills
