### ISSUE TITLE
duplicate members on roll call vote positions

### ISSUE THREAD

**Issue by russellsamora** [propublica/congress-api-docs#235]
For example:
{ congress: '115', chamber: 'House', session: '1', roll_call: '1'}

Tulsi Gabbard (G000571) is returned 3 times in the positions array.

**Comment by dwillis** [comment]
@russellgoldenberg I just pulled this url from the API: https://api.propublica.org/congress/v1/115/house/sessions/1/votes/1.json

I only see Gabbard listed once. Can you check again that this the URL that's causing issues for you?

**Comment by russellsamora** [comment]
logged url: https://api.propublica.org/congress/v1/115/House/sessions/1/votes/1.json
saved result straight to disk: https://gist.github.com/russellgoldenberg/de3486ec780c776c924a829fd8780ec9

Using the request library with Node. Can share code if helpful.

**Comment by dwillis** [comment]
@russellgoldenberg Gotcha, I see it. Should be fixed shortly.
