### ISSUE TITLE
Invalid JSON due to line breaks in bill titles

### ISSUE THREAD

**Issue by hrecht** [propublica/congress-api-docs#237]
Hi, I've run across a few invalid JSONs due to line breaks appearing in bill titles using the member vote positions API. This breaks certain JSON parsers. Ideally the fix would be to remove these line breaks.

Here's one example:
`curl "https://api.propublica.org/congress/v1/members/B000444/votes.json?offset=3280"
  -H "X-API-Key: PROPUBLICA_API_KEY"`

Invalid section:
```
{
           "member_id": "B000444",
           "chamber": "Senate",
           "congress": "105",
           "session": "2",
           "roll_call": "314",
           "vote_uri": "https://api.propublica.org/congress/v1/105/senate/sessions/2/votes/314.json",
           "bill": {
             "bill_id": "hr4328-105",
             "number": "H.R. 4328",
             "sponsor_id": "W000672",
             "bill_uri": "https://api.propublica.org/congress/v1/105/bills/hr4328.json",
             "title": "Making omnibus consolidated and emergency appropriations for the fiscal 
year ending September 30, 1999, and for other purposes.",
             "latest_action": "Became Public Law No: 105-277."
           },
           "amendment": {
           },
                     "description": "Conference Report H.R. 4328; Women&#39;s Health and Cancer Rights Act of 1998",
           "question": "On the Conference Report",
           "result": "Agreed to",
           "date": "1998-10-21",
           "time": "09:02:00",
           "total":              {
               "yes": 65,
               "no": 29,
               "present": 0,
               "not_voting": 6
           },
           "position": "Yes"
         },
```

**Comment by hrecht** [comment]
Relatedly, found when searching for any similar issue reports - I would encourage not adding additional line breaks to the json response. https://github.com/propublica/congress-api-docs/issues/187

**Comment by dwillis** [comment]
@hrecht thanks - we'll try to nail those stray line breaks down.

**Comment by dwillis** [comment]
These should be resolved now (or very soon, depending on API caching).

**Comment by hrecht** [comment]
That seems to be fixed but I'm getting a new error with the same call now - in the same line, the line break is gone but there is now an invalid tab between the period and end quotes.
`"title": "Making omnibus consolidated and emergency appropriations for the fiscal year ending September 30, 1999, and for other purposes.	",`

**Comment by dwillis** [comment]
@hrecht Argh, fixing now. Give it a bit for the cache to clear.

**Comment by hrecht** [comment]
Thank you! I'm actually seeing a slightly different reason for the error using JSONLint now so maybe it wasn't the tab messing up my parser? Unclear, but it's something in that line.
<img width="1168" alt="Screen Shot 2019-09-03 at 12 45 50 PM" src="https://user-images.githubusercontent.com/9753760/64192512-d7807d00-ce48-11e9-8d4a-dd24d92a3504.png">

**Comment by dwillis** [comment]
Just checked the results with the JSONLint validator and it seems ok now.

**Comment by hrecht** [comment]
It's working for me now too, thanks so much for the quick fix.
