### ISSUE TITLE
Some votes endpoint offsets throwing errors

### ISSUE THREAD

**Issue by hrecht** [propublica/congress-api-docs#239]
I'm running into errors in the recent votes endpoint for a small percentage of offset numbers. I don't see any clear pattern but am consistently getting errors on the same calls.
Some examples:
https://api.propublica.org/congress/v1/senate/votes/recent.json?offset=1420
https://api.propublica.org/congress/v1/senate/votes/recent.json?offset=1440
https://api.propublica.org/congress/v1/senate/votes/recent.json?offset=2640
https://api.propublica.org/congress/v1/house/votes/recent.json?offset=2940
https://api.propublica.org/congress/v1/house/votes/recent.json?offset=2960

I get a status code of 200, but the text of the response says `{"status":"500","error":"Internal Server Error"}`

**Comment by dwillis** [comment]
@hrecht this should be fixed now
