### ISSUE TITLE
Get bills by member with types other than "introduced" and "updated"

### ISSUE THREAD

**Issue by ndawg** [propublica/congress-api-docs#242]
Would it be possible to allow the endpoint for getting bills by a member to accept all types of bill states? That is: `introduced`, `updated`, `active`, `passed`, `enacted`, and `vetoed`, just like the endpoint to get recent bills.

**Comment by dwillis** [comment]
@ndawg seems reasonable, yeah.

**Comment by dwillis** [comment]
@ndawg the only one of those that is tricky is `passed`, because that requires a chamber parameter, since a bill can be passed by neither the House or Senate, by one of those chambers or by both. The current endpoint doesn't really provide a way to account for those without requiring a chamber parameter.

**Comment by ndawg** [comment]
@dwillis personally, I would consider `passed` to logically mean passed both chambers. As in, it has passed through congress and is now waiting to be enacted. But I understand the difficulty with being precise about that.

**Comment by dwillis** [comment]
@ndawg I'd be ok with supporting a `passed` that meant passed both chambers. Would just need to make that clear in the docs, I think.

**Comment by dwillis** [comment]
@ndawg this is done now ([docs](https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills-by-a-specific-member)).

**Comment by ndawg** [comment]
@dwillis Thanks for this. I've found a few bugs. These two requests:

```
https://api.propublica.org/congress/v1/members/S000033/bills/updated.json?offset=0
https://api.propublica.org/congress/v1/members/S000033/bills/introduced.json?offset=0
```

Return malformed JSON (they have dangling commas on the last bill in the `bills` array). This doesn't seem to occur with the other responses.

Also, this minor error message. When the `member-id` is missing, the following error is given:
```
{
    "status": "ERROR",
    "copyright": "Copyright (c) 2019 Pro Publica Inc. All Rights Reserved.",
    "errors": "Please specify a congress"
}
```
Which should probably say "Please specify a member" instead. That had me confused for a few minutes.

**Comment by dwillis** [comment]
@ndawg the malformed JSON is fixed now. I'll work on the error message.

**Comment by ndawg** [comment]
Looks fixed, thanks!
