### ISSUE TITLE
Get Related Bills returns more than 20 results

### ISSUE THREAD

**Issue by ndawg** [propublica/congress-api-docs#245]
The "Get Related Bills" endpoint appears to return every single related bill possible. For example, for the following query:
```
https://api.propublica.org/congress/v1/116/bills/hr1/related.json
```
There are 74 entries in the `related_bills` field. Meanwhile, the documentation says:

> This request returns the 20 most recent results and supports paginated requests.

**Comment by dwillis** [comment]
@ndawg This is fixed now.

**Comment by ndawg** [comment]
Looks good, thanks!
