### ISSUE TITLE
Get Subjects for Bill returns more than 20 results

### ISSUE THREAD

**Issue by ndawg** [propublica/congress-api-docs#246]
The "Get Subjects for a Specific Bill" endpoint appears to return every subject possible. For example, for the following query:

```
https://api.propublica.org/congress/v1/116/bills/hr1/subjects.json
```

There are 73 entries in the `subjects` field. Meanwhile, the documentation says:

> This request returns the 20 most recent results and supports paginated requests.

**Comment by dwillis** [comment]
@ndawg this is fixed now.

**Comment by ndawg** [comment]
Looks all good to me. Thanks!
