### ISSUE TITLE
Get Senate Nomination Votes is missing some minor fields

### ISSUE THREAD

**Issue by ndawg** [propublica/congress-api-docs#247]
This is a pretty minor issue, but there are a few fields missing from the response of the 'Get Senate Nomination Votes' endpoint: `chamber` (which is always 'senate'), `source`, `url`, `vote_uri`. All the data required to supplement these values exist in the given response, but it would be nice to have it be consistent with other voting endpoints.

**Comment by dwillis** [comment]
@ndawg this is done.

**Comment by ndawg** [comment]
@dwillis looks like the new fields are all there, however I'm now getting a dangling comma on the last result of the array, causing any strict parser to fail. Here's a sample response: https://jsoneditoronline.org/?id=acac33587a4d4d5b9ce2cd2a83c2664e

**Comment by dwillis** [comment]
@ndawg Ok, that should be fixed.

**Comment by ndawg** [comment]
Looks good. Thanks!
