### ISSUE TITLE
Invalid JSON on Compare Two Members Vote Positions endpoint 

### ISSUE THREAD

**Issue by renderorange** [propublica/congress-api-docs#250]
The following URI returns invalid JSON:
```
https://api.propublica.org/congress/v1/members/W000647/votes/Z000013/100/senate.json
```

The documentation mentions the range of congress for senate and house:
https://projects.propublica.org/api-docs/congress-api/members/#compare-two-members-vote-positions
```
102-116 for House, 101-116 for Senate
```

If you choose members within a congress outside of the range, in this case:
```
100 - senate
W000647 - first-member-id
Z000013 - second-member-id
```
`agree_percent` and `disagree_percent` return as `NaN`, which fails JSON validation.
```
"agree_percent": NaN,
"disagree_percent": NaN
```

**Comment by dwillis** [comment]
@renderorange Choosing congresses outside the range specified does result in an error, which is why the docs say not to do it. We'll change the result to a generic error message, but you shouldn't expect valid results from that request.

**Comment by renderorange** [comment]
The JSON should still be valid though, that's more of what I was going for with this issue.

**Comment by dwillis** [comment]
@renderorange Understood, but it's not a request that we support nor one that users should be making.

**Comment by renderorange** [comment]
👍

**Comment by dwillis** [comment]
@renderorange Ok, requests using congresses outside the range of values now yield an error message rather than a response with invalid JSON.

**Comment by renderorange** [comment]
Thank you!
