### ISSUE TITLE
500 error response from Members Get Recent Privately Funded Trips

### ISSUE THREAD

**Issue by renderorange** [propublica/congress-api-docs#252]
The following request fails with 500 error:
https://api.propublica.org/congress/v1/110/private-trips.json
```
{
   "error" : "Internal Server Error",
   "status" : "500"
}
```
congress 111 and 112 also fail.
congress 113-116 succeed as expected.

**Comment by dwillis** [comment]
@renderorange This should be resolved now. Thanks!

**Comment by renderorange** [comment]
Thank you!
