### ISSUE TITLE
members.json in_office boolean attribute doesn't appear to change results

### ISSUE THREAD

**Issue by renderorange** [propublica/congress-api-docs#254]
The documentation at https://projects.propublica.org/api-docs/congress-api/members/#lists-of-members mentions an `in_office` boolean attribute to `filter the list to only active members (or to see members who have left)`, but I can't seem to get the result set to change when using it.

I'm using the following:
https://api.propublica.org/congress/v1/116/house/members.json?in_office=false
and seeing both true and false in the output.
```
$ curl -s -i -H "X-API-Key: $PP" 'https://api.propublica.org/congress/v1/116/house/members.json?in_office=FALSE'|grep '"in_office": true'|wc -l
437
$ curl -s -i -H "X-API-Key: $PP" 'https://api.propublica.org/congress/v1/116/house/members.json?in_office=FALSE'|grep '"in_office": false'|wc -l
8
```

Am I using this attribute incorrectly, or is there something I'm missing?

**Comment by dwillis** [comment]
@renderorange The docs aren't clear enough; the request itself can't be filtered via the URL, but the response can be filtered post-request.

**Comment by renderorange** [comment]
Ah, that makes sense.  Thanks for the clarification!
