### ISSUE TITLE
offset for Lists of Members is not paginating

### ISSUE THREAD

**Issue by renderorange** [propublica/congress-api-docs#255]
The offset argument for Lists of Members does not appear to be paginating the results.

https://api.propublica.org/congress/v1/102/house/members.json?offset=20
```
          'results' => [
                         {
                           'num_results' => 448,
                           'offset' => 0,
```

Does this endpoint support offset?  Generally speaking, if the results from an endpoint include an offset key, is that a safe indication that it supports pagination?

**Comment by dwillis** [comment]
@renderorange Lists of members do not support offset; they provide the full listing of members who have served in that chamber and congress: https://projects.propublica.org/api-docs/congress-api/members/#lists-of-members

**Comment by renderorange** [comment]
Thanks for the follow up.
