### ISSUE TITLE
Invalid JSON response for senate floor updates

### ISSUE THREAD

**Issue by njgingrich** [propublica/congress-api-docs#256]
When requesting from this endpoint:
https://api.propublica.org/congress/v1/senate/floor_updates/2020/03/25.json

You receive the following (truncated) JSON:

```json
{
	"results": [
		...
		{
				"congress": "116",
				"chamber": "Senate",
				"timestamp": "2020-03-26 01:01:17 -0400",
				"date": "2020-03-25",
				"action_id": "",
				"description": "The Senate agreed to the following nominations by Voice Vote, en bloc.
				Cal.#570, Charles Williams, of Missouri to be an Assistant Secretary of the Navy.
Cal. # 631,
				William Jordan Gillis,
				of Georgia,
				to be an Assistant Secretary of Defense.
				",
				"bill_ids": []
		},
		...
	]
}
```

Which is called out as invalid JSON because of the newlines, specifically called out as `SyntaxError: JSON.parse: bad control character in string literal at line 143 column 91 of the JSON data` in the Firefox devtools.

(Can also be seen pretty much anywhere there are nominations, such as https://api.propublica.org/congress/v1/senate/floor_updates/2020/03/23.json).

**Comment by dwillis** [comment]
Took way too long to fix this, but it is now fixed.
