### ISSUE TITLE
Unclear as to how bill updating works

### ISSUE THREAD

**Issue by LukeClancy** [propublica/congress-api-docs#257]
at https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills

is a bill added to the top of the "updated" list when its info is recently changed? Or is it based on latest_major_actions? Currently I am redownloading alot of data every day because I am afraid it might of been changed. I am looking for an efficient way to determine when the bills receive changes through the api to avoid that.

Clearly explaining this in the documentation would be nice. And if a "recently changed" Type to query is not a feature, that would be a nice feature. Also please note that this is an issue with rollcalls and other endpoints as well.

If I am making a mistake as to the nature of how these areas are updated (maybe they are not changed at all unless it is added or there is a latest_major_action) that would be nice to know as-well and would be nice in the documentation.

**Comment by dwillis** [comment]
@LukeClancy Thanks for the question, and I'm sorry that the docs aren't clearer on this. For the `updated` list, the sort key is `latest_major_action_date` in descending order, so when that value is updated, the order in which a bill would appear changes. We check for updated bill information several times a day.

Because the changes to bills can be frequent and many, we don't have an endpoint that represents any or every change, such as the addition of a cosponsor or the addition of a short title. If you want to be able to see those sorts of changes as soon as they are recorded in the data, my suggestion would be to use our [bulk legislative data download](https://www.propublica.org/datastore/dataset/congressional-data-bulk-legislation-bills) that gives you the XML and JSON representations of all bills. It is updated every day.

I think the situation is different from roll call votes, which are almost never changed after the fact, but if you have a case where you feel we're not making it easy to use that data, I'd be interested in learning more about it.

**Comment by LukeClancy** [comment]
Hey dwillis, I have been updating my infrastructures efficiency in relation to the database and it has been helping greatly to my bulk data downloads. I will also be updating my api capabilities to include a persistent connection which I think will also help. Bulk bill data wont help for me since I am also utilizing rollcalls and rollcall votes, along with members.

During my downloading of rollcall votes I have noticed that all votes on [congress 115, house, session 1, rollcall 104] have been duplicated. for example:

[{rollcall_id: "115-house-1-104", member_id: "Z000017", vote_position: "Yes"}, {rollcall_id: "115-house-1-104", member_id: "Z000017", vote_position: "Yes"}], [{rollcall_id: "115-house-1-104", member_id: "Z000018", vote_position: "Not Voting"}, {mmrollcall_id: "115-house-1-104", member_id: "Z000018", vote_position: "Not Voting"}] )

are two of the many members votes that have been duplicated.

Is there an area to report this and other kinds of database irregularities?

Thanks for your help,

Luke Clancy

**Comment by dwillis** [comment]
@LukeClancy - thanks for pointing this out, and this is the place to do so. We've removed the duplicate records for that vote.

**Comment by LukeClancy** [comment]
Thats great! I am currently going through all active bills, and calling both the endpoint for the particular bill and its cosponsors (down to 113th congress).

Here is an endpoint which consistently just returns 500 server error, taken from the [latest active endpoint](https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills), bill_uri parameter.

`curl -H "X-API-Key: #################" https://api.propublica.org/congress/v1/116/bills/s2731.json`

I expect that I will come across more issues like this due to the amount of data I will be going through. I will post these here in curl format for easy confirmation on your end. Just replace ### in api key and run in a terminal

**Comment by dwillis** [comment]
@LukeClancy thanks, that's helpful. I will say that your use case is exactly what the bulk bill data is for, though, and it will cut down on both errors and time.

**Comment by LukeClancy** [comment]
Yeah but I'm doing the same thing with rollcalls though, and there is no bulk for that

**Comment by dwillis** [comment]
Right, but as those are two separate things, I definitely would recommend using the bulk bill data for just that bit.

**Comment by LukeClancy** [comment]
I will think about it. The issue is that my infrastructure for the API method is already built, and in comparison to roll-calls (of which there are many), updating bills in a similar manner seems insignificant

**Comment by LukeClancy** [comment]
But you are right, looking at it the bulk update would be a lot more efficient

**Comment by dwillis** [comment]
There are many, many more bills than there are roll calls votes, fwiw.

**Comment by LukeClancy** [comment]
really? Oh I thought it was the other way around, since I figured you needed a rollcall to vote on a bill, amendment etc. I dont really get the political stuff and I'm working by myself

**Comment by LukeClancy** [comment]
allright I'll do it, thanks for the help! It goes farther back than the API too so its probably for the best

**Comment by dwillis** [comment]
Yeah, most bills - even the ones that see any actions - don't get a vote.
