### ISSUE TITLE
how to get the indivdiual member votes of a partiuclar Vote

### ISSUE THREAD

**Issue by pseuGithup** [propublica/congress-api-docs#258]
Apologies, if this is the wrong forum for this question.

My question is this. Say I have a Bill, and I want to know how individual members (senate and/or congress) voted on that bill. How would I best go about getting this information?

Looking at the Votes section of the API (https://projects.propublica.org/api-docs/congress-api/votes/), it seems the votes are rolled up to the party level (republican, democratic, independent, and total); as in the following example. 

Is there any way to get the individual votes per Bill and its corresponding Votes?

Thank you in advance for any help/insight. 

"results": {
        "chamber": "House",
        "offset": 0,
        "num_results": 20,
        "votes": [{
                "congress": 115,
                "chamber": "House",
                "session": 1,
                "roll_call": 438,
                "source": "http://clerk.house.gov/evs/2017/roll438.xml",
                "url": "http://clerk.house.gov/evs/2017/roll438.xml",
                "vote_uri": "https://api.propublica.org/congress/v1/115/house/sessions/1/votes/438.json",
                "bill": {
                    "number": "S.114",
                    "bill_id": "s114-115",
                    "api_uri": "https://api.propublica.org/congress/v1/115/bills/s114.json",
                    "title": "To authorize appropriations and to appropriate amounts for the Veterans Choice Program of the Department of Veterans Affairs, to improve hiring authorities of the Department, to authorize major medical facility leases, and for other purposes.",
                    "latest_action": "Became Public Law No: 115-46."
                },
                "amendment": {},
                "question": "On Passage",
                "description": "Department of Veterans Affairs Bonus Transparency Act",
                "vote_type": "YEA-AND-NAY",
                "date": "2017-07-28",
                "time": "12:52:00",
                "result": "Passed",
                "democratic": {
                    "yes": 186,
                    "no": 0,
                    "present": 0,
                    "not_voting": 8,
                    "majority_position": "Yes"
                },
                "republican": {
                    "yes": 228,
                    "no": 0,
                    "present": 0,
                    "not_voting": 12,
                    "majority_position": "Yes"
                },
                "independent": {
                    "yes": 0,
                    "no": 0,
                    "present": 0,
                    "not_voting": 0
                },
                "total": {
                    "yes": 414,
                    "no": 0,
                    "present": 0,
                    "not_voting": 0
                }
            },

**Comment by dwillis** [comment]
@pseuGithup this is definitely the right forum, and you can get individual vote positions on the [response for each vote](https://projects.propublica.org/api-docs/congress-api/votes/#get-a-specific-roll-call-vote). In the example you cite above, it would be https://api.propublica.org/congress/v1/115/house/sessions/1/votes/438.json.

**Comment by pseuGithup** [comment]
thank you for responding. That's what I was looking for. 

Now there is a follow-up question. I have a large number of **bills** I received, now my aim is to retrieve the **votes** for those specific bills.

It's not entirely clear to me how I would link those bills to the roll-call-number.

In other words, how would I retrieve the votes for a bill, if I don't know the **roll-call-number**, but only the **bill_id**?

I hope my question makes sense.

**Comment by dwillis** [comment]
@pseuGithup Sure, each [bill response](https://projects.propublica.org/api-docs/congress-api/bills/#get-a-specific-bill) includes a `votes` array that contains any votes on that bill. You should be aware that some bills have several votes - including possibly multiple "passage" votes - and many others have none.
