### ISSUE TITLE
Votes by Date  -- attributes of democratic, republican, and independent votes

### ISSUE THREAD

**Issue by pseuGithup** [propublica/congress-api-docs#259]
so I am currently implementing pulling down **Votes by Date.**
[votes by date](https://projects.propublica.org/api-docs/congress-api/votes/#get-votes-by-date)

what I notice is that vote results for each party affiliation (democratic, republican, and independent) are generally reported in this format.

**Democratic:**
     - yes
     - no
     - present
     - not_voting
     - majoirty_position

       "democratic": {
             "yes": 41,
             "no": 5,
             "present": 0,
             "not_voting": 0,
             "majority_position": "Yes"
            },
           "republican": {
             "yes": 51,
             "no": 0,
             "present": 1,
             "not_voting": 0,
             "majority_position": "Yes"
            },
           
However, at some point, my code tripped on this JSON fragment (see bold)

 {
           "congress": 115,
           "chamber": "House",
           "session": 1,
           "roll_call": 2,
           "source": "http://clerk.house.gov/evs/2017/roll002.xml",
           "url": "http://clerk.house.gov/evs/2017/roll002.xml",
           "vote_uri": "https://api.propublica.org/congress/v1/115/house/sessions/1/votes/2.json",
           "bill": {},
           "question": "Election of the Speaker",
           "question_text": "",
           "description": "Electing Paul Ryan of Wisconsin as Speaker of the House",
           "vote_type": "YEA-AND-NAY",
           "date": "2017-01-03",
           "time": "14:04:00",
           "result": "Ryan (WI)",
           **_"democratic": 
           {"Pelosi":189,"Ryan (OH)":2,"Cooper":1,"Not Voting":1,"Lewis (GA)":1},
           "republican": 
           {"Ryan (WI)":239,"Webster":1,"Not Voting":1},
           "independent": 
           {},
           "total": 
           {"Ryan (WI)":239,"Pelosi":189,"Ryan (OH)":2,"Cooper":1,"Webster":1,"Not Voting":2,"Lewis (GA)":1}_**
          },

As such, should I assume that attributes of vote results can vary quite a bid, rather than being fixed to, say,  
     - yes
     - no
     - present
     - not_voting
     - majoirty_position

Any thoughts are much appreciated.

**Comment by dwillis** [comment]
Some votes, such as the Election of a Speaker in the House, do not have the conventional Yes/No/Present choices. Instead, members vote by declaring the name of the person they support.

**Comment by pseuGithup** [comment]
ok thanks, Derek for clarifying, I thought so. I'll reflect this in my code.
