### ISSUE TITLE
search whether person is lobbyist?

### ISSUE THREAD

**Issue by ArnoviMoinuddin** [propublica/congress-api-docs#261]
Hello! 

I'm trying to write up some code that would check whether or not somebody is a lobbyist. When looking at the documentation for "Get a Specific Lobbying Representation filing," I see that the parameters are "id." How can I translate a name to an ID? Alternatively, can I query by name?

**Comment by dwillis** [comment]
@ArnoviMoinuddin Hi! You can search by name using the "[Search Lobbying Representation filing](https://projects.propublica.org/api-docs/congress-api/other/#search-lobbying-representation-filings)" endpoint.
