### ISSUE TITLE
Invalid JSON Response for Bill Search

### ISSUE THREAD

**Issue by emilguareno** [propublica/congress-api-docs#263]
Hello!

I am using the Propublica API to search for bills in Congress. One of the requests returned a JSON response with one of the bills having a `control` character on the Summary field which is considered invalid JSON.

![image](https://user-images.githubusercontent.com/9509310/96328922-f87c4100-0ffc-11eb-98cf-1538288d8aaf.png)

This is the request: https://api.propublica.org/congress/v1/bills/search.json?query="hr6210"

**Comment by dwillis** [comment]
@emilguareno thanks for this report - we'll have it fixed later today.
