### ISSUE TITLE
Last_Vote attribute null in Bill endpoints

### ISSUE THREAD

**Issue by jonhsmiht** [propublica/congress-api-docs#264]
Based on this previously resolved issue - https://github.com/propublica/congress-api-docs/issues/177, it appears the `last_vote` attribute is no longer populated, always comes back as `null`

Can be seen at these endpoints - https://api.propublica.org/congress/v1/116/senate/bills/enacted.json?offset=20, as well as in the API documentation - https://projects.propublica.org/api-docs/congress-api/bills/#get-recent-bills.

Is this a deprecation or perhaps a regression? 

Thanks!

**Comment by dwillis** [comment]
Hi @jonhsmiht - I'm not sure this is a bug; I can find the `last_vote` for some of the bills in those responses. Rather, many of the bills that have been enacted this congress have been passed without a roll call vote in either chamber, either by voice vote or unanimous consent.

**Comment by jonhsmiht** [comment]
Hi @dwillis - I do now see some `last_vote` attributes coming through for some bills, as you mentioned, had been mostly seeing blank, but thanks for the explanation! I will close this issue out now.
