### ISSUE TITLE
When will Congressional Committee data for 117 congress be added?

### ISSUE THREAD

**Issue by RoseMarieSecada** [propublica/congress-api-docs#267]
No results returned for committees or members for 117th congress. When will they be added?
https://api.propublica.org/congress/v1/117/house/committees.json

**Comment by dwillis** [comment]
@vizyourgov It's on the list - if you'd like to help with that effort, please let us know.

**Comment by RoseMarieSecada** [comment]
happy to help depending on what's involved

**Comment by RoseMarieSecada** [comment]
Hi. I’d love to help depending on what’s involved.Just let me know...

**Comment by dwillis** [comment]
The House is the main issue. The process involves taking resolutions like [this one](https://www.congress.gov/bill/117th-congress/house-resolution/95/text) and populating a data file at the United States project [here](https://github.com/unitedstates/congress-legislators/blob/master/committee-membership-current.yaml). We use that file as the source of our committee membership data. We use the official resolutions to determine the dates when a member is appointed to and/or leaves a committee.

In addition, I'm not positive that all committee assignments have been made (to say nothing of subcommittee assignments). This isn't an overnight process, unfortunately. It takes many hours.

**Comment by RoseMarieSecada** [comment]
Looking at this, it seems like it has been done manually in the past. Is that correct?

I did a little poking around in wikipedia and see that a lot of work has been done in this space. For example: https://en.wikipedia.org/wiki/117th_United_States_Congress#Committees <https://en.wikipedia.org/wiki/117th_United_States_Congress#Committees>

I’m wondering what you think of leveraging this to automate the gathering of members and then merging the bioguide info etc into the format you need.

If you’re okay with this and I am able to do it, i can give you the scripts for future use.

**Comment by dwillis** [comment]
@vizyourgov that might work, yeah - if you're interested i'd definitely give it a look.

**Comment by RoseMarieSecada** [comment]
Attached is an example of what I was able to do for house subcommittees with a combination of wikipedia data and my local databases. The first tab has some notes and questions about how you’d like to proceed..

**Comment by dwillis** [comment]
@vizyourgov I don't see an attachment?

**Comment by vizyourgov** [comment]
the attachment is an excel spreadsheet with multiple tabs which i see cannot be

**Comment by RoseMarieSecada** [comment]
the attachment is an excel sheet with multiple tabs. Here it is a zipped version.

[House Subcommittee Data Example.xls.zip](https://github.com/propublica/congress-api-docs/files/6083820/House.Subcommittee.Data.Example.xls.zip)

**Comment by RoseMarieSecada** [comment]
I uploaded a zip file of an excel workbook with house committee and sub-committee data. It’s a starting off point to get a sense of how you view the various sources.  

The idea is to end up with something akin to this json of senate, committees, subcommittees, and members of both. 

I use senate.gov <http://senate.gov/> as the source for committees, subcommittees, and members and I enrich the member data with the bioguide id and other info.  I can run it on demand, automatically creating the json file. I can modify as needed - this is only an example.  Same can be done for house but wikipedia is probably a better source. 






p.s.  Surely some member of congress knows if a reliable version of this data exists somewhere else…

**Comment by RoseMarieSecada** [comment]
here is a json file with all the house committee and subcommittee data including leadership and members as found on wikipedia. i enriched with bioguide id, urls, etc. note: the member data taken from wikipedia is for 117th congress when/where it exists. it will be for 116th congress when 117th doesn't exist but that is indicated as is the wikipedia url used.
i can change this as needed but wanted to share just in case.

[gov_house_committees.json.zip](https://github.com/propublica/congress-api-docs/files/6103228/gov_house_committees.json.zip)

**Comment by dwillis** [comment]
@vizyourgov Thanks! I'll take a look. In the meantime I'm happy to report that we have full committee assignments in the API for the 117th.
