### ISSUE TITLE
missing votesmart id for new members of congress

### ISSUE THREAD

**Issue by RoseMarieSecada** [propublica/congress-api-docs#268]
missing votesmart id for new members of congress

i can get these for you if it'll help include in the API

**Comment by dwillis** [comment]
@vizyourgov we source member information from this effort: https://github.com/unitedstates/congress-legislators, which does have votesmart ids, although it might not have the newest folks. If you had them for any that project is missing we'd welcome a contribution there.

**Comment by RoseMarieSecada** [comment]
i just downloaded the csv file and found Votesmart ID to be missing from new members of congress.

I’m happy to look these up on votesmart and provide them.

**Comment by dwillis** [comment]
@vizyourgov thanks!

**Comment by RoseMarieSecada** [comment]
Attached is a zipped excel sheet with the missing votesmart ids added in red.   
[congress_legislators.xlsx.zip](https://github.com/propublica/congress-api-docs/files/6118022/congress_legislators.xlsx.zip)

**Comment by RoseMarieSecada** [comment]
Here is a python dictionary with all the missing votesmart ids mapping to their bioguide ids.

    votesmart_dictionary = {
                "A000148": "173832", "B000668": "102400", "B000740": "152294", "B000825": "191290",
                "B001223": "191205", "B001224": "169020", "C001039": "191306", "C001054": "143749",
                "C001055": "3422", "C001104": "188527", "C001116": "189770", "D000032": "137655",
                "F000246": "115056", "F000470": "3882", "F000472": "191355", "G000597": "143103",                       
                "G000061": "188664", "G000582": "47514", "G000594": "178867", "G000595": "190745",
                "G000596": "189785", "G000591": "179667", "H001086": "190524", "H000273": "71547",
                "J000304": "188325", "J000020": "59772", "J000305": "179414", "J000306": "191209",
                "K000396": "167669", "K000377": "190594", "L000266": "107024", "L000273": "189882",
                "M000194": "146076", "M000317": "127929", "M000871": "125007", "M001135": "178304",                     
                "M001136": "191633", "M001186": "191586", "M000687": "26892", "M001211": "187988",
                "M001212": "121792", "M001213": "191164", "M001214": "113775", "N000192": "177075",
                "O000019": "151831", "O000174": "176134", "O000086": "191166", "P000145": "59742",
                "P000048": "188165", "R000305": "41560", "S001204": "185972", "S000929": "178203",
                "S001135": "157194", "S001159": "80596", "T000165": "51831", "T000486": "161718",
                "W000790": "189794", "W000788": "176751"}
