### ISSUE TITLE
Include district's Census GEOID in members endpoint

### ISSUE THREAD

**Issue by mhkeller** [propublica/congress-api-docs#27]
Using [members.json endpoint](https://projects.propublica.org/api-docs/congress-api/endpoints/#lists-of-members), it would be helpful if items included the `GEOID` of the district to easily join data to [Census Congressional shapes](https://www.census.gov/geo/maps-data/data/cbf/cbf_cds.html). 

This field is *usually* the two character FIPS code and a two character district ID. For Vermont and others with at-large seats, though, this doesn't work. Vermont, for example, returns `'1'` as the district but the Census `GEOID` is `'5000'`.

**Comment by dwillis** [comment]
Hey @mhkeller - we've added a `geoid` attribute to the House members endpoint (do you think it would be useful for Senate?). Please check it out and let me know what you think.

**Comment by mhkeller** [comment]
Thanks for adding it so quickly. Looks good except I'm seeing trailing commas inside the `geoid` string.

<img width="633" alt="screen shot 2017-05-31 at 5 53 28 pm" src="https://cloud.githubusercontent.com/assets/498744/26655741/1a49528c-462a-11e7-9439-2acb8fc0901a.png">

**Comment by dwillis** [comment]
@mhkeller ack. should be fixed now.

**Comment by mhkeller** [comment]
Awesome. Last thing I'm seeing is empty strings for Guam (GU), Puerto Rico (PR), American Samoa (AS), U.S. Virgin Islands (VI), Northern Mariana Islands (MP) and DC.

**Comment by dwillis** [comment]
Should be good now.

**Comment by mhkeller** [comment]
And of course these don't follow the pattern of ending in `00`. Looks like they all end in `98`. Census has:

* `PR` -> `7298`
* `VI` -> `7898`
* `GU` -> `6698`
* `AS` -> `6098`
* `MP` -> `6998`
* `DC` -> `1198`

**Comment by dwillis** [comment]
Got it - fixed now!
