### ISSUE TITLE
How often does the Floor Actions endpoint update?

### ISSUE THREAD

**Issue by kfranzen** [propublica/congress-api-docs#28]
Hi I am working on an app related to voter engagement and direct democracy. 

It looks like the Floor Actions endpoint is only updating once per day currently. Is there any plan for that endpoint to update more frequently?

**Comment by dwillis** [comment]
Hi @kfranzen. The floor actions endpoint is definitely updated more than once a day - it's updated every 30 minutes. Is there a particular day you're looking at?

**Comment by kfranzen** [comment]
Hey @dwillis Yeah. Sorry I was a little hasty with my question. Apologies. I was looking at the Senate data for today. It has only one entry from earlier this morning, but no updates. The morning entry seems to indicate there should be some more activity.

I pull the house data for today and realized it is much more current than I thought.

**Comment by dwillis** [comment]
No worries - let me check on the Senate loader.

**Comment by dwillis** [comment]
These endpoints update every 30 minutes.
