### ISSUE TITLE
Null response

### ISSUE THREAD

**Issue by EightArmCode** [propublica/congress-api-docs#280]
Sometimes I just get a null response from this API. My code has not changed from the last time I used it, but the service is unavailable. I have looked and do not find a status page or any way to receive updates about planned maintenance. It's currently returning null, so I figured I would use the downtime to ask about service uptime. Is there anything to learn about how to better weather these periods of inaccessibility?

Best regards

**Comment by dwillis** [comment]
@EightArmCode thanks - I think the API should be up and running again now, but in general if you get a null response our suggestion is to retry the call.

**Comment by EightArmCode** [comment]
Cheers. Thanks for the reply.

A status page would be stellar, in case it ever comes up in planning. 👌🏼
