### ISSUE TITLE
Kyrsten Sinema's party property is invalid

### ISSUE THREAD

**Issue by EightArmCode** [propublica/congress-api-docs#281]
Hello - thanks for the API 👋 

This is extremely minor, but just wanted to call attention to the fact that Kyrsten Sinema's party is returning as `I`

The other democrat legislators are returning `D`.

**Comment by njgingrich** [comment]
FWIW, Kyrsten Sinema is now an Independent as of Dec 2022: https://www.reuters.com/world/us/arizonas-sinema-switches-political-affiliation-independent-politico-2022-12-09/

**Comment by dwillis** [comment]
@EightArmCode @njgingrich The senators with a party of `ID` caucus with the Democrats. Sinema does not, and therefore we have her as an `I`
