### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by jermatic** [propublica/congress-api-docs#288]
Since some time yesterday, i am getting 504s .. got a 500 at some point in the day but then back to 504

**Comment by Lbongard** [comment]
I'm experiencing the same. Some requests seem to work on the 3rd or 4th attempt.

**Comment by Jack-Aaron** [comment]
Same issue for the following requests that I've tried:
https://api.propublica.org/congress/v1/members/XNNNNN.json
https://api.propublica.org/congress/v1/118/house/members.json

**Comment by mahmoudamr512** [comment]
Experiencing same issue

**Comment by mahmoudamr512** [comment]
@Jack-Aaron Any person had luck?

**Comment by c0nnortbtx** [comment]
Been having this problem for a few weeks.

**Comment by AlexRosario** [comment]
Glad I'm not the only experiencing these issues. It's completely stopped working for me today.

**Comment by white-paper-proj** [comment]
Same here, getting 504 errors with all requests.

**Comment by Jack-Aaron** [comment]
> @mahmoudamr512 Any person had luck?

Same. Now all requests are responding 504.

**Comment by AlexRosario** [comment]
No, luck right now. I created a recursive fetch function and it would work
on 2nd or 3rd last night though

**Comment by rkendel1** [comment]
It’s still not working anyone had any luck?

**Comment by dwillis** [comment]
Folks, my apologies for the outages and the delay in responding. I _think_ that we have resolved most of the issues with gateway timeouts, but it did come at a cost: we've had to dial back on pagination on statement requests, limiting those to a maximum of 200 results, because among other factors we were being buried in requests for those.

Please let me know if you're continuing to see issues with the API.

**Comment by rkendel1** [comment]
Still getting this
{
    "status": "500",
    "error": "Internal Server Error"
}

**Comment by dwillis** [comment]
@rkendel1 can you post the actual request you're making that yields that error? Most of the previous week's errors were 504 gateway timeouts, but yours is different.

**Comment by rkendel1** [comment]
I think I'm all set now.

**Comment by Jack-Aaron** [comment]
I'm no longer getting the 504 errors. Thank you, @dwillis !
