### ISSUE TITLE
Source availability?

### ISSUE THREAD

**Issue by showerst** [propublica/congress-api-docs#289]
@dwillis  I saw the recent email about the project shutting down. 

One piece of data that doesn't appear to be available elsewhere is the statements feed (member press releases). Would it be possible to make the source code for this available? I might be willing to take it on either personally or under the umbrella of Openstates.

Thanks!

**Comment by dwillis** [comment]
@showerst My plan is to host the press releases as bulk data after the API shuts down. The source code for scraping the press releases will be open sourced at that time.

**Comment by showerst** [comment]
Thanks!
