### ISSUE TITLE
Any plan to expose the congressional calendars via an api?

### ISSUE THREAD

**Issue by kfranzen** [propublica/congress-api-docs#29]
I would like to show the schedule of upcoming votes and other actions in an app form. I am currently exploring several of the other api endpoints, but I was wondering if there is any plan to expose the posted congressional calendars and/or scheduled votes through an endpoint?

**Comment by dwillis** [comment]
Hi @kfranzen: we do plan to add an endpoint for upcoming bills to be debated on the House and Senate floor, but as the congressional schedule changes fairly often it's unlikely that we'd do scheduled votes.

**Comment by kfranzen** [comment]
@dwillis Thanks for the update. Knowing what is being debated would be great. I am working on setting up an app around more direct voter engagement and education and I would at some point like to have an idea of when things will be voted on.
