### ISSUE TITLE
500 internal server error on statements/subject endpoint.

### ISSUE THREAD

**Issue by zdalexander512** [propublica/congress-api-docs#30]
I'm getting a 500 internal server error at this endpoint: https://api.propublica.org/congress/v1/statements/subject/affordable-care-act-repeal.json

I'm also getting the same error while testing in Postman, so was wondering if this is something on my end or if this is an invalid endpoint. It seems to be happening with others as well (i.e. "immigration, etc.).

Thanks

**Comment by dwillis** [comment]
Thanks, @zdalexander512. This should be fixed very shortly.

**Comment by zdalexander** [comment]
Great, thanks so much @dwillis!

**Comment by dwillis** [comment]
Yep, fixed now. Sorry about that!

**Comment by zdalexander** [comment]
No problem at all, thanks!
