### ISSUE TITLE
Amendments End point num_results empty

### ISSUE THREAD

**Issue by jden1705** [propublica/congress-api-docs#31]
The num_results value on the Amendments end point is coming back empty and causing some errors parsing the json. 

Used https://jsonlint.com/ to validate the json. 

Experienced issue on the following two calls: 
https://api.propublica.org/congress/v1/111/bills/hr3590/amendments.json
https://api.propublica.org/congress/v1/115/bills/hr21/amendments.json

full json from second call: 

{
	"status": "OK",
	"copyright": "Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
	"results": [{
		"congress": "115",
		"bill_id": "hr21-115",
		"num_results": ,
		"offset": 0,
		"amendments": []
	}]
}

Thanks.

**Comment by dwillis** [comment]
Thanks @jden1705. This issue is resolved now. Please note that the amendments response is subject to pagination.
