### ISSUE TITLE
Get a specific member endpoint committee should have chamber field

### ISSUE THREAD

**Issue by epanchenko** [propublica/congress-api-docs#32]

**Comment by dwillis** [comment]
@epanchenko Because each member role in the `roles` attribute has a `chamber` attribute, that value also applies to the committees in the `committees` attribute. Does that make sense? The one exception would be for joint committees, I guess.

**Comment by epanchenko** [comment]
I am worried about the joint committees.  If the committee ids all start with the chamber H- House, S - Senate, J - Joint, then I will not need the field.  Do you know if that naming of the committee codes is consistent with the chamber?

**Comment by dwillis** [comment]
It is, yes.
