### ISSUE TITLE
Difference in bioguide ID field name in similar endpoints

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#40]
The list of members returns an `id` field inside of the `members` array. On the endpoint to find a specific member, it uses a `member_id` field. 

This was confusing during development for me -- I recommend using the most explicit version, `member_id`, consistently.

**Comment by dwillis** [comment]
I think we can do that - it would be a breaking change, so probably would be a v2 thing.

**Comment by konklone** [comment]
I ended up making this a slightly larger issue, in #42, which would be similarly breaking. Closing this one in favor of that one.
