### ISSUE TITLE
Communicating "At-Large" representatives

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#41]
Does the Pro Publica API have a preferred way of communicating that a representative is "At-Large"?

Right now, it looks like this is represented by a district of `1`. However, there's no way to distinguish this at parse-time from a representative of the 1st District in a state with multiple districts.

The Sunlight Congress API managed this by using a district of `0` for At-Large representatives. Any ideas/plans for doing this in the Pro Publica API?

**Comment by dwillis** [comment]
This is a good question. I'm not hugely in favor of using `0` as a district number, mostly because it makes it seem like it's not a district in some respects. We could add a `display_district` attribute that would have something like "At-Large" as a value.

**Comment by konklone** [comment]
That'd work, though it'd also suggest that you'd be putting a display version of every district in there, not just At-Large ones. An `at_large` value of `true` might do the same thing and be more surgical.

**Comment by dwillis** [comment]
Sure, that's an easy add.

**Comment by dwillis** [comment]
We've added `at_large` to Get Member responses; would it help to have for Member lists as well?

**Comment by konklone** [comment]
Thank you! And yes, having it be in member lists would be helpful too, as the client I work on lists district representation in list views.

**Comment by dwillis** [comment]
These are done.

**Comment by konklone** [comment]
This is really nitpicky, but the `at_large` field in the JSON is oddly inconsistent in line breaks (which made it hard to visually scan and see what was happening). 

The `at_large` is appended to an existing line:

```json
           "leadership_role": null,
           "fec_candidate_id": "H6AK00045",
           "seniority": "46",
           "district": "1", "at_large": true,
           "ocd_id": "ocd-division/country:us/state:ak/cd:1",
```

Anyway, this is valid JSON and it all works, just noting an oddity that could hamper debugging.

**Comment by konklone** [comment]
The above was from a member fetch endpoint. I don't see the `at_large` field in the member list by state/district endpoint:

https://api.propublica.org/congress/v1/members/house/AK/current.json

```json
{
   "status":"OK",
   "copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "id": "Y000033",
         "name": "Don Young",
         "first_name": "Don",
         "middle_name": null,
         "last_name": "Young",
         "role": "Representative",
         "gender": "M",
         "party": "R",
         "times_topics_url": "http://topics.nytimes.com/top/reference/timestopics/people/y/don_young/index.html",
         "twitter_id": "RepDonYoung",
         "facebook_account": "RepDonYoung",
         "youtube_id": "RepDonYoung",
         "seniority": "46",
         "next_election": "2018",
         "api_uri": "https://api.propublica.org/congress/v1/members/Y000033.json",
         "district": "1"
      }
]}
```

**Comment by dwillis** [comment]
We'll add it - sorry, in the initial discussion I only asked about Get Member and Member List responses.

**Comment by konklone** [comment]
Oh, I thought "member list" referred to a category of endpoints that returned plural legislators. I will refer to the state/district separately from the other member list endpoint.

**Comment by dwillis** [comment]
Nah, I just need to broaden my mind :-)

**Comment by dwillis** [comment]
Would it help with the current member response mirrored the entirety of the Get Member response?

**Comment by konklone** [comment]
That would certainly simplify parsing. Though one mildly complicating factor is that I do think including the `roles` and other large sub-arrays would be too heavy for large plural endpoints. On the Get Member response, some of the fields now put directly on the member list endpoints (e.g. `party`, `state`, `district`) are on roles (and then party is mirrored on the top-level as `current_party`). 

So there's some naming inconsistency there, but broadly speaking, it's nice to be able to run the same parsing code to extract core legislator details from a set of legislator metadata, whether it's from Get Member or a member list endpoint.

**Comment by dwillis** [comment]
Ok, yeah. I think if we can agree on a set of top-level attributes those should be available in most responses, with detail stuff like `roles` left for detail responses.
