### ISSUE TITLE
Putting individual name fields on state/district member lists

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#46]
The state/district member endpoint only returns a `name` field, but none of the `first_name`, `last_name`, and `middle_name` fields.

This causes issues for clients who are trying to sort based on last name (without resorting to error-prone string splitting), or in general try to create a basic set of data about a member from a list endpoint.

Could the 3 individual name fields also appear on the state/district endpoint?

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Thank you!
