### ISSUE TITLE
Guidance for assembling YouTube and Facebook URLs

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#47]
The Twitter URLs are self explanatory, but it's not clear how to reliably create YouTube URLs (is it a channel or a user?) or Facebook URLs (is it a Page or a user?). 

These were resolved in the Sunlight API by using the numeric ID version of the IDs contained in the unitedstates/congress-legislators project, but I am not as certain about reliably using the string versions seen in the Pro Publica API.

Do you already have some suggested client logic for constructing appropriate URLs? Is it safe to just append the value to the end of `youtube.com/` or `facebook.com/`?

**Comment by dwillis** [comment]
In both cases, you can append the value to the end of `youtube.com/` or `facebook.com`.

**Comment by konklone** [comment]
Thanks. It might be helpful to mention this in the docs somewhere, but I'm satisfied with the explanation.
