### ISSUE TITLE
Consistently slow response times

### ISSUE THREAD

**Issue by cpsubrian** [propublica/congress-api-docs#48]
For requests like:

```
time curl https://api.propublica.org/congress/v1/111/house/sessions/1/votes/70.json -H 'x-api-key: [your key]'
```

I'm seeing response times typically over 2.5 seconds. This really slows down processes that need to load several votes (say to tally a legislator's position across them). Given that this is a GET request for a highly-cacheable resource, these response times surprise me.

Shouldn't these things be cached and very fast to retrieve? Am I missing headers or other request details that defeat whatever caching I should be hitting?

**Comment by dwillis** [comment]
@cpsubrian We're looking into this.

**Comment by cpsubrian** [comment]
@dwillis Awesome 👍  Let me know if I can do anything to help, or just follow-up test.

**Comment by dwillis** [comment]
@cpsubrian can you test the vote responses out now? i think we've been able to speed them up a bit.

**Comment by cpsubrian** [comment]
@dwillis From Rome (traveling right now) its under a second now (0.7-0.9), and I suspect stateside would be even a bit faster. Still not *blazing* but a absolute improvement. Thanks!
