### ISSUE TITLE
Time field on votes uses inconsistent formatting between endpoints

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#56]
When looking at a bill's embedded `votes`, a vote `time` is `"16:48"`, but on a roll call endpoint, it's `"16:48:00"`. It'd be helpful to have this be a consistent format.

This can be done separately from #55, which I filed essentially as a new field request.

**Comment by dwillis** [comment]
As a precursor to #55, I've made the two consistent; they now appear as `"16:48:00"`.
