### ISSUE TITLE
Bill number field could be formatted more usefully

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#57]
And there's no way to get just the `hr21` portion of a `bill_id` (which the bill details endpoint needs). In addition, the `bill` and `number` fields appear redundant, and it seems like the `number` field was intended to have this portion of the slug.

Here's the first part of a bill when fetched directly:

```json
{
        "bill_id": "hr21-115",
        "congress": "115",
        "bill": "H.R.21",
        "bill_type": "hr",
        "number": "H.R.21",
```

The `bill` field and `number` field are identical. And if someone wanted to use this data to construct the fetch URL (which ends in `hr21.json`), they would either need to do a string split on the hyphen in `bill_id`, or would need to do some text operations on the `bill` or `number` fields to lowercase the field and remove the dots.

I recommend that `number` be turned into the `hr21` slug partial, for consistency and ease of URL construction.

**Comment by dwillis** [comment]
@konklone is this from a votes response?

**Comment by konklone** [comment]
No, this is from fetching a specific bill.

**Comment by dwillis** [comment]
Does the `bill_uri` attribute help in this scenario?

**Comment by konklone** [comment]
It's predictable, but you still have to do string splitting. This is not a huge deal and easy enough to work around, but I think having clients do string splitting is probably not what was intended.

**Comment by dwillis** [comment]
No, I mean the bill_uri is in the response.

**Comment by konklone** [comment]
Yep, I understood that - I meant you'd have to string-split the `bill_uri` field to extract the substring before the `.json` at the end and after the last `/`.

**Comment by dwillis** [comment]
I'm sorry, I'm not following - why do you need that substring?

**Comment by konklone** [comment]
Now I get your point - you could use the `bill_uri` as returned instead of constructing it dynamically. That makes sense intuitively, but generally inside of a "client library" context you're not constructing requests via full URLs, but by a library of functions that dynamically constructs URLs based on API endpoint patterns. 

So for example, in [my client implementation's URL construction method](https://github.com/konklone/congress-android/blob/f38508a20e391e61f69fdeb754b7b5ef0bc03acc/app/src/main/java/com/sunlightlabs/congress/services/ProPublica.java#L54-L104), the base URI of the Pro Publica API is swappable, and full URLs are constructed at call-time depending on certain query string parameters and pagination.

I want to be clear that this whole issue is pretty low-priority, and I've already worked around it (with string-splitting), but I'm trying to be consistent about documenting where I spy bits of friction in client implementation. My particular client implementation is in a statically typed and fairly "heavyweight" language (Java), and so is perhaps a bit different and more constrained than client implementation might be in a more dynamic and lightweight language like Ruby or Python.

**Comment by dwillis** [comment]
Gotcha. Ok, we can add a `bill_slug` attribute that has that.

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Verified. Thank you!

**Comment by Rosina9700** [comment]
Hi, 

A question relating to this - why do some values for bill_slug have _x or _y following them? What is the difference? 

Thanks!

**Comment by dwillis** [comment]
Can you give me an example?

**Comment by Rosina9700** [comment]
Yeah sure thing!
Here are my steps:
-> get recent votes through recent votes end point
-> for each recent vote get bill_uri and vote_uri attributes
-> get specific bill and vote roll call information through API calls to bill_uri and vote_uri
-> manipulate the data so I have dataframe where each row is a representative and each column is a bill and the value the vote. 
-> For each bill (column), I assign the column name as the variable 'bill_slug' from the bill API call.

For some bills, I get 'bill_slug' values that look like this:
- hr244_x
- hr244_y 
etc

Any ideas? Thanks for the quick response

**Comment by dwillis** [comment]
Hi @Rosina9700 I'm having trouble replicating this. Can you provide the request URL where the response includes a `bill_slug` value of hr244_x or hr244_y?
