### ISSUE TITLE
Cannot Use Elizabeth Warren's ID for "Get a Specific Member’s Vote Positions"

### ISSUE THREAD

**Issue by zdalexander512** [propublica/congress-api-docs#6]
Not able to ajax request using Elizabeth Warren's ID number: W000817

**Comment by dwillis** [comment]
Hi @zdalexander512, can you say more about this? The proper url to retrieve her vote positions would be https://api.propublica.org/congress/v1/members/W000817/votes.json. How are you attempting to retrieve it?

**Comment by zdalexander512** [comment]
Sure thing, I have an ajax GET request set up to retrieve her vote positions. However, I can't pull this data into the console on my browser. I've been able to successfully pull in other data through your API, however this specific instance is giving me trouble. My ajax request is below: 

<script>

$(function(){

var $test = $('#test');
var $congress_not = $('#congress_not');
	
	$.ajaxSetup({
		beforeSend: 
		function(xhr) {	
			xhr.setRequestHeader("X-API-Key","5buFoSrpgu70owCTEcp7Z3mjThGka24f5SW8EyJA")
		},
	});

	$.ajax({
		url: "https://api.propublica.org/congress/v1/members/W000817/votes.json", 
		success: 
		function (data) {
			$(data.results).each(function(index, value) {
				console.log(value);
				$.each(value.members, function(index, value) {
					console.log(value);
			          });
			});
		}
	});
});

</script>

Any ideas why this may not be working? Thanks.

**Comment by dwillis** [comment]
I don't think this is an API error, since the call itself works and I was able to get a 200 response in the JS console locally. The `results` attribute has an additional `votes` attribute; perhaps you need to call that instead of `value.members`?

**Comment by zdalexander512** [comment]
Alright thanks for checking! Yeah, I'm also getting a 200 response on my end locally, but for some reason the console is coming up blank. I did switch `value.members` to `value.votes`, but I'm still getting the same result. I realized too that this result is not just for Elizabeth Warren, but for other Senators as well. It must be something with my code. I'll keep troubleshooting, thanks!
