### ISSUE TITLE
Vetoed and enacted are ambiguous

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#60]
The docs don't show whether `vetoed` and `enacted` are booleans or dates.

I'd prefer they be dates, so I can infer both the boolean value and the date simultaneously. Or, if they are booleans, then a date field be added alongside them.

**Comment by dwillis** [comment]
They are both dates; I'll update the docs.

**Comment by dwillis** [comment]
This is done: https://projects.propublica.org/api-docs/congress-api/bills/
