### ISSUE TITLE
Are House/Senate passage votes only present if successful?

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#61]
There's no field for the result of a House or Senate passage vote. So, are the `house_passage_vote` and `senate_passage_vote` fields only set to dates when passage was successful? Or will they be filled when the passage vote fails as well? How should clients consider these fields?

**Comment by dwillis** [comment]
They are only filled upon successful passage.

**Comment by konklone** [comment]
Thanks!

**Comment by konklone** [comment]
(Reopening as a suggestion to say so in the docs somewhere.)

**Comment by dwillis** [comment]
In the docs now.

**Comment by konklone** [comment]
Confirmed, thank you!
