### ISSUE TITLE
Breaking bug: invalid JSON on enacted date

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#62]
On H.R. 1362, which became law, the `enacted` field is unquoted:

```json
         "house_passage": "2017-03-06",
         "senate_passage": "2017-03-14",
         "enacted": 2017-03-20,
```

I have the JSON captured here:
https://konklone.io/json/?id=cf1e92f71e365b2f49d3bf00ffefb604

This breaks strict JSON parsing attempts entirely.

**Comment by konklone** [comment]
Less severe, but the docs show these fields as empty strings instead of `null` in at least one case. I haven't observed this in the wild yet, but wanted to flag that in case it's an easy check/fix.

**Comment by dwillis** [comment]
I need to finish updating the docs examples, but they should not be empty strings in any case in the actual API responses.

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
Confirmed!
