### ISSUE TITLE
Allow 'both' for recent bills of all types

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#63]
You can use a `both` value for `chamber` in the list of recent bills, but only for `passed` bills. It would be useful to be able to do one call to list `introduced`, `updated`, `enacted`, and `vetoed` bills, since I don't think users really care about the chamber the bills originate from in these states.

This is especially useful to combine server-side instead of client-side, because of pagination.

**Comment by konklone** [comment]
From a priorities perspective, this one's a bit higher than others I've filed, as the only way I can implement this (without the time-expensive process of creating new native UI) is doing client-side merging and sorting, which is impossible to do without unexpected results when only sorting a page at a time. 

Basically, when the House and Senate introduce bills at different rates, their pages will be tracking different time spans, and so "page 5" for each chamber may be wildly divergent spans of time -- even when merged and sorted per-page, the page barriers will see jumps back and forth in dates.

Certainly not the end of the world, and maybe this isn't a big deal to most clients, but I wanted to articulate here the client-side impact on my end.

**Comment by dwillis** [comment]
This change will be live shortly.

**Comment by konklone** [comment]
Confirmed!
