### ISSUE TITLE
What field are bills sorted on for different types of recent lists?

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#68]
Recent bills can be `introduced`, `updated`, `passed`, `enacted` or `vetoed`. Does the order in which results are sorted also change in response to the type passed in? 

The most natural sort order for each type would probably be:

* `introduced`: `introduced_date`
* `updated`: `latest_major_action_date`
* `passed`: [not sure, there's not one uniform field across both chamber?]
* `enacted`: `enacted`
* `vetoed`: `vetoed`

But whatever it is, it'd be helpful to document it.

**Comment by konklone** [comment]
I'm using `introduced`, `updated`, and `enacted` in my client, and it seems like they might be following my table above. But I can currently only look at one page at a time, so I am not sure.

**Comment by dwillis** [comment]
This is now documented here: https://projects.propublica.org/api-docs/congress-api/endpoints/#get-recent-bills

**Comment by konklone** [comment]
Yes it is! Thank you.
