### ISSUE TITLE
Providing the same fields for cosponsors as for sponsors

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#69]
The cosponsors of a bill only get `cosponsor_id` and `name` fields. It'd be helpful to have `cosponsor_state` and `cosponsor_party` fields, and (similar to #64) a `cosponsor_title` field.

**Comment by dwillis** [comment]
The titles for this and #64 - is the abbreviated title what you want, or the full one?

**Comment by konklone** [comment]
Either one would work. I personally think that he abbreviated titles are the simplest thing to work with across the API. They can be inflated into longer titles just as easily, and I think appending `, 3rd class` to Senator titles is rarely what's desired when showing titles that are frequently formatted as `Sen. Ron Johnson`.

**Comment by dwillis** [comment]
We've added `cosponsor_state` and `cosponsor_party` fields. Working on the other stuff.

**Comment by konklone** [comment]
I can't verify this change because of a 500 error I'm getting on the cosponsors endpoint, which I reported in #76.

**Comment by dwillis** [comment]
Should be good to go now.

**Comment by konklone** [comment]
Verified! Thank you!
