### ISSUE TITLE
Request: list of active bills

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#71]
The list of `updated` bills doesn't really filter to the same signal-to-noise ratio as a list of `active` bills (where they've gone beyond introduction and referral). The API does have an `active` flag on individual bills, but no way to filter on that flag right now. This is a feature request for that flag.

**Comment by dwillis** [comment]
Yeah, we'll do this.

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Confirmed! Thank you!
