### ISSUE TITLE
Phrasal search vs multi-keyword search

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#72]
The bill search endpoint suggests the user give a string via a `query` parameter. Some questions that come up:

* If multiple words are given (e.g. `query=health care`) is it treated as a phrase or as multiple keywords? 
* If it's multiple keywords, is it an `AND` or an `OR`?
* If it's multiple keywords, can it be turned into a phrase by quoting the words (e.g. `query="health care"`)

**Comment by jeremybmerrill** [comment]
@konklone the query gets piped into ElasticSearch's querystring search.

> If multiple words are given (e.g. query=health care) is it treated as a phrase or as multiple keywords?

as multiple keywords

> If it's multiple keywords, is it an AND or an OR?

OR, but documents with both/all keywords will usually be ranked higher than those with only one.

> If it's multiple keywords, can it be turned into a phrase by quoting the words (e.g. query="health care")

Yep! you can also do stuff like exclude words by searching `query=megahertz -kilohertz` if you hate laws about narrowband communications.

**Comment by konklone** [comment]
Got it. This is pretty similar to [what the old Sunlight API does](https://sunlightlabs.github.io/congress/#full-text-search), though Sunlight set the default logical operator to `AND` instead of `OR` based on Sunlight's perception of what would be more intuitive to users (or really just most familiar to them from years using Google). 

In any case, I think documenting the behavior would be helpful.

**Comment by dwillis** [comment]
Have updated the docs.

**Comment by konklone** [comment]
:+1:
