### ISSUE TITLE
Bill searching by relevance

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#73]
One aspect of the Sunlight Congress API's bill text search was that it would let you sort by recency or by relevance. The relevance search can be helpful when folks are looking for The Bill That Everyone Is Talking About. This is a request for that feature.

**Comment by jeremybmerrill** [comment]
I believe we have something approximating this already (see https://github.com/propublica/congress-api-docs/issues/74) but if the relevance results are in practice not very good, we should consider coming up with a better or more Sunlight-y version of it.

**Comment by konklone** [comment]
Gotcha. The [docs currently say](https://projects.propublica.org/api-docs/congress-api/endpoints/#search-bills) it's sorted by recency, which is why I filed this and #74:

> Use this request to search the title and full text of legislation by keyword to get the 20 most recent bills.

But as I said in https://github.com/propublica/congress-api-docs/issues/74#issuecomment-317605741, the best option would be to have both, since they both can play pretty crucial roles.

**Comment by konklone** [comment]
This is resolved. Thank you!
