### ISSUE TITLE
Ordering for searching of recent bills is unclear/buggy

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#74]
When I perform a search for `megahertz`, I can't ascertain what order the results are in. The API doesn't document which field is used for the sorting (it just says `recent` bills), but I think it may not be sorting them in the intended manner, as all the dates I can see jump back and forth as I go down the list.

**Comment by jeremybmerrill** [comment]
This may be intended behavior, but we may want to change what we intend...

ElasticSearch's querystring search, which we're using as of last week, does its own fancy thing for (default) sorting. It's meant to, I think, encapsulate an intuition about what documents (i.e. bills) are more "about" a given query -- something like if `megahertz` shows up a bunch in one bill but only once in the second, the first bill is ranked higher. 

I'd certainly believe that this leads to a nonsensical sort order, at least in some cases. @dwillis: what do you think?

**Comment by jeremybmerrill** [comment]
@konklone: What would you think about adding the ability to specific a sort option in the URL? E.g. `?query=megahertz&sort=last_major_action_date:desc`

**Comment by konklone** [comment]
> @konklone: What would you think about adding the ability to specific a sort option in the URL? E.g. ?query=megahertz&sort=last_major_action_date:desc

I would love that!

The old Sunlight Congress API has this feature, and it also allowed you to sort on `_score`, an ElasticSearch special field (at least at the time) to explicitly call for ES' relevance-based search, while allowing the server more flexibility behind the scenes in evolving what factors and weightings went into calculating the `_score` over time.

In either case, I think allowing the ability to sort by either "relevance" or "recency" is pretty crucial, because sometimes users want one and sometimes they want the other.

And for those who want to get notifications of new bills matching a certain phrase (which was a very common use case by Sunlight employees and many other power users), it's really only viable to do that with recency-based sorting, since the order has to be predictable.

**Comment by konklone** [comment]
Just a request to let me know if you think you'll end up supporting a recency-based text search any time in the pretty-near future. I can deal either way, but it will impact a decision I'll have to make on whether I disable existing user push notification subscriptions for the "latest bills matching X" in my next release migrating to the Pro Publica API.

**Comment by dwillis** [comment]
I think we will but cc @jeremybmerrill

**Comment by jeremybmerrill** [comment]
@konklone soon... quite soon, unless something bad happens.

**Comment by konklone** [comment]
:+1: :smiley_cat:

**Comment by jeremybmerrill** [comment]
Nothing bad happened. Change'll be deployed within the hour.

`?query=megahertz&sort=_score&dir=asc` will get you bill from least relevant to most. 

Now by default, sorting in the API is most recent to least recent. Options for `sort` are `_score` or `date`. Options for dir are `asc` and `desc`, defaults to `desc`.

Sorting in the web app continues to be most relevant to least relevant.

**Comment by dwillis** [comment]
These changes are deployed now. Updating docs.

**Comment by konklone** [comment]
This is looking good! I do spy (I think) a bug in sorting, though - neither the `introduced_date` nor `latest_major_action_date` seem to be the ordering field. I'm not sure what the sorting field is. (The query string parameter is just `date`, but I would expect `introduced_date` for this endpoint.)

Here's each in turn, using the first page:

```
curl -s "https://api.propublica.org/congress/v1/bills/search.json?offset=0&dir=desc&query=%22health+care%22&sort=date" -H "X-API-Key: XOutAiJOWXaaQsGpQAOd86hFzZ1X0dL61C0U0GBe" | jq .results[0].bills[].introduced_date
"2017-07-13"
"2017-06-07"
"2017-07-13"
"2017-07-13"
"2017-07-13"
"2017-05-16"
"2017-07-12"
"2017-05-26"
"2017-06-07"
"2017-06-07"
```

```
curl -s "https://api.propublica.org/congress/v1/bills/search.json?offset=0&dir=desc&query=%22health+care%22&sort=date" -H "X-API-Key: [redacted]" | jq .results[0].bills[].latest_major_action_date
"2017-07-13"
"2017-07-25"
"2017-07-25"
"2017-07-13"
"2017-07-13"
"2017-07-17"
"2017-07-12"
"2017-07-12"
"2017-07-12"
"2017-07-12"
```

**Comment by jeremybmerrill** [comment]
Oh I think I know what I did. Easy to fix, if I'm right. (Accidentally
sorting by ID among the top 10 by date)

It ought to be ordering by latest major action date... Should introduced
date definitely be what it sorts by, in your view? Are there use cases for
both?

Jeremy B. Merrill

**Comment by konklone** [comment]
Actually, now that I think it through, the latest major action date makes more sense than the introduction date -- specifically because we'd want to be able to detect when text is added to a later version of a bill. 

If it were sorted by introduction date, then text added later would cause the bill to suddenly match the search feed, but would not get floated to the top, and so would get missed by anyone watching the top of the feed (and ultimately any client watching the feed has to choose a reasonable "top" to watch).

That said -- can you comment (and document) on how this feed behaves when new bill versions are released? What "bill versions" are full-text-search-indexed at any given time for a given "bill"?

**Comment by jeremybmerrill** [comment]
@konklone Just for a public update, the issue looks to be that some data isn't getting passed thru to ElasticSearch, so the sorting is accurate for a previous version of the data. Working on getting that figured out...

**Comment by jeremybmerrill** [comment]
@konklone Can you give this another look? I think I've fixed the problem and a spot-check seems to give the right results, but I'd love another set of eyes.

(Underlying issue was that data was out of sync between ElasticSearch and the DB.)

**Comment by konklone** [comment]
@jeremybmerrill Well, when I ask for `offset=0`, it gives me 10 results, and they appear to be ordered correctly.

But when I supply `offset=20`, I get the same 10 bills all over again:

```
curl -s "https://api.propublica.org/congress/v1/bills/search.json?offset=20&dir=desc&query=%22health+care%22&sort=date" -H "X-API-Key: [redacted]" | jq .results[0].bills[].latest_major_action_date

"2017-07-28"
"2017-07-28"
"2017-07-28"
"2017-07-27"
"2017-07-24"
"2017-07-24"
"2017-07-24"
"2017-07-24"
"2017-07-20"
"2017-07-20"
```

(I filed #86 to cover the separate bug around getting 10 bills back at a time instead of 20.)

**Comment by jeremybmerrill** [comment]
Ah, okay. Interesting. Is this a regression relative to the ProPublica API in the past, or a thing we need to add for parity with Sunlight?

In either case, we'll get it fixed, just as a guide for me in where to look. And also in either case, I won't be able to look at it until probably Thursday at the earliest.

**Comment by konklone** [comment]
No, this doesn't have anything to do with Sunlight features, this and #86 are straight bugs in the Pro Publica API -- it can't paginate through search results, and the pages are the wrong size.

**Comment by jeremybmerrill** [comment]
Right, definitely gonna get it fixed. Just so I can get a lead on where the
problem might be, do you know if this is a new problem with the ProPublica
API (like in the past two weeks) or did it never work?

Jeremy B. Merrill

**Comment by jeremybmerrill** [comment]
@konklone okeedoke, check it out. I think I've implemented this to match the docs (and #86 too). I appreciate your help in checking it, since you're such an active user of the API. Lemme know how it works.

**Comment by jeremybmerrill** [comment]
FWIW the Congress app's bill search pagination now works. (That's what was misbehaving before, right?)

**Comment by konklone** [comment]
@jeremybmerrill The issues with getting 10 results instead of 20 are resolved.

However, it looks like there are still some issues - the endpoint isn't sorting by date as expected, and some of the newest bills don't appear until page 2.

Here are the `latest_major_action_date`'s of page 1 (`offset=0`):

```
$ curl -s "https://api.propublica.org/congress/v1/bills/search.json?offset=0&dir=desc&query=%22health+care%22&sort=date" -H "X-API-Key: [redacted]" | jq .results[0].bills[].latest_major_action_date
"2017-08-02"
"2017-08-02"
"2017-07-28"
"2017-07-28"
"2017-07-28"
"2017-07-27"
"2017-07-24"
"2017-07-24"
"2017-07-24"
"2017-07-24"
"2017-07-20"
"2017-07-20"
"2017-07-31"
"2017-07-19"
"2017-07-19"
"2017-07-18"
"2017-07-18"
"2017-07-18"
"2017-07-13"
"2017-07-25"
```

There are a couple of out of place dates in page 1, and the earliest date is August 2nd.

On page 2 (`offset=20`), the order breaks down further, and it has some bills with an action dated August 3rd:

```
$ curl -s "https://api.propublica.org/congress/v1/bills/search.json?offset=20&dir=desc&query=%22health+care%22&sort=date" -H "X-API-Key: [redacted]" | jq .results[0].bills[].latest_major_action_date
"2017-07-13"
"2017-08-01"
"2017-07-13"
"2017-07-13"
"2017-08-03"
"2017-08-03"
"2017-07-12"
"2017-07-12"
"2017-07-12"
"2017-07-12"
"2017-07-11"
"2017-07-11"
"2017-07-11"
"2017-07-11"
"2017-07-11"
"2017-07-11"
"2017-07-26"
"2017-07-11"
"2017-07-11"
"2017-07-11"
```

**Comment by jeremybmerrill** [comment]
This looks like the same issue as before with the dates: the dates are updated in MySQL (which is where the data in the feed comes from), but not in ElasticSearch (which is what does the ordering). I'll look into it...

**Comment by jeremybmerrill** [comment]
I manually updated the data in the ElasticSearch, which was failing due to an unrelated XML parse issue elsewhere. That should *mostly* fix the issue. There's still some scattered instances of this problem (where the date in MySQL is newer than the one in ElasticSearch) that I'm looking into.

**Comment by konklone** [comment]
I subscribed myself to push notifications for recent bills matching `"health care"`, and one thing I've been noticing is that I've been getting notifications for bills whose dates are older than the most recent. In other words, they're appearing in a sort of backfilling of the first page of results, instead of at the front of the queue.

**Comment by jeremybmerrill** [comment]
The root cause of all this is still a little unclear to me, but I found a *possible* cause (a loader that didn't fire callbacks, leading to updates in MySQL that didn't propagate to ElasticSearch) and addressed it. Hopefully that'll fix the issue going forward... we'll see in the next couple of days.

(I suspect why you were seeing that "backfilling" behavior is that stuff was getting updated sporadically when some subset of actions happened to the bills, causing them to actually propagate to ElasticSearch.)

**Comment by konklone** [comment]
Got it. It being a couple of days later, I'll let you know if I see this behavior happening again from now on.
