### ISSUE TITLE
500 error on cosponsors endpoint

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#76]
Using the URL in the docs for the cosponsors endpoint:

https://api.propublica.org/congress/v1/114/bills/hr4249/cosponsors.json

I get a 500 error:

```json
{"status":"500","error":"Internal Server Error"}
```

Maybe related to #69?

**Comment by konklone** [comment]
Just to be comprehensive, this also happens on a bill in the most recent session:

https://api.propublica.org/congress/v1/115/bills/hr2786/cosponsors.json

**Comment by dwillis** [comment]
Should be fixed now, and new cosponsor fields added.

**Comment by konklone** [comment]
Yep, this is fixed!
