### ISSUE TITLE
Is the senate updates endpoint updating? My latest updates are from 7/18.

### ISSUE THREAD

**Issue by zdalexander512** [propublica/congress-api-docs#78]
I'm using the endpoint https://api.propublica.org/congress/v1/115/senate/floor_updates.json and am getting updates only up to July 18th. Is this happening with others? I know this endpoint should update every half-hour or so.

**Comment by dwillis** [comment]
@zdalexander512 Hmm, seems like it wasn't updating. We're investigating. The other endpoints are not affected.

**Comment by zdalexander512** [comment]
Great, thanks @dwillis.

**Comment by dwillis** [comment]
Senate floor updates should be working again, but I will need to keep an eye on that in short term.

**Comment by zdalexander512** [comment]
Great, yeah they are working on my end too. Thanks for looking into this @dwillis.
