### ISSUE TITLE
Sunlight API merger: Bill responses

### ISSUE THREAD

**Issue by dwillis** [propublica/congress-api-docs#8]
[Sunlight's bill responses](https://propublica.github.io/congress/bills.html) have a number of fields that we aim to include in the ProPublica API. The plan is to use the existing ProPublica Congress API [bill responses](https://propublica.github.io/congress-api-docs/#bills) and add Sunlight response data and functionality to them.

The following Sunlight fields will be added in bill list responses:

* `bill_id` (in Sunlight data an example would be `hr1936-114`)
* `bill_type`
* `enacted`
* `active`
* `vetoed`
* `congressdotgov_url`
* `govtrack_url`
* `summary`
* `summary_short`

In addition, the following Sunlight fields will be added to bill detail responses:

* `sponsor_party`
* `sponsor_state`
* `last_vote_date`
 
In addition, we will be supporting [Sunlight's bills `search` request](https://propublica.github.io/congress/bills.html#billssearch). 

We will not be supporting the filtering syntax that Sunlight uses for its responses. Some of the same functionality is available in current ProPublica responses; if there are specific filters that users feel strongly about that we do not support we'll consider adding them.

**Comment by dwillis** [comment]
These changes have been made in the API. See examples [here](https://propublica.github.io/congress-api-docs/#bills)

**Comment by radditude** [comment]
Do you plan to keep the [/upcoming_bills](https://propublica.github.io/congress/upcoming_bills.html) response?

**Comment by dwillis** [comment]
@radditude That's something we're figuring out in the next couple of weeks. I'd like to think we can retain it, though.

**Comment by markdboyd** [comment]
Is bill search by keyword supported by the new API? I don't see an endpoint listed for it in the documentation: https://projects.propublica.org/api-docs/congress-api/endpoints/#bills

**Comment by dwillis** [comment]
Hi @markdboyd - not yet, but it will be soon.

**Comment by konklone** [comment]
> > Do you plan to keep the /upcoming_bills response? I'd like to use it in a project I'm working on, but I'll go a different route if it will be deprecated soon.
> 
> @radditude That's something we're figuring out in the next couple of weeks. I'd like to think we can retain it, though.

@dwillis Did you end up deciding not to keep the `/upcoming_bills` data? It's the only other "what's coming up" information beyond hearings, and there's machine-readable data for it (at least in the House). It's been valuable enough that I've surfaced it in the home screen of the Congress app for a while.

**Comment by konklone** [comment]
To add some data -- I went and looked in current analytics - looks like people click through to an "upcoming" bill ~200 times a day across my particular client application, so pretty active use.

**Comment by carlossilva** [comment]
Is an /upcoming_bills api endpoint available? It is a core piece we currently use from the Sunlight API. Please let me know.

**Comment by dwillis** [comment]
It will be by tomorrow, yes, but only for the House for the near future. The Senate has changed how it displays this information and we're working on a solution. Note that both chambers responses from the Sunlight API are currently empty.

**Comment by carlossilva** [comment]
Thanks @dwillis how often and when would you be running the code that gathers this info? The timeliness of this data is paramount to us as we further summarize these bills before we send them out to the public before they are voted on in congress. We check for new upcoming bills every 30 minutes as we would like to know this information as soon as possible.

What we have observed is that even though these upcoming bills are published in the house calendars on Friday, we don't get these through the sunlight API until Monday morning. Getting them as soon as they appear on the house calendar would be ideal.

**Comment by dwillis** [comment]
We currently update bill information 5 times a day and the upcoming bills loader would be run as part of those updates. Those updates run every day, meaning that if a calendar was updated on Friday evening it would be picked up that night or early Saturday morning, depending on when it was published.

**Comment by carlossilva** [comment]
Sounds great, thanks for supporting this API. There are only two filter params we use currently, "order", and "legislative_day__gt" to only ask for the upcoming bills since yesterday for example. Would something similar be offered in your endpoint?

**Comment by dwillis** [comment]
We're not supporting filtering params like Sunlight did (see other Sunlight notes [here](https://projects.propublica.org/api-docs/congress-api/sunlight/)); instead the response will default to bills expecting to be considered that day. We can talk about whether that's too restrictive, though.

**Comment by carlossilva** [comment]
I think that is too restrictive as when a bill is scheduled to be voted on is not an exact date and could be given in ranges like "in the next week" and hence the reason I think the sunlight api defaulted to returning only bills in the future and immediate past (7 days ago). For us the key would be to return any bills that are coming up when submitting the query and in the future (really only one week ahead as the house seems to publish for the upcoming week the Friday before). Hope this makes sense.

**Comment by dwillis** [comment]
Yeah, it does. Given that we've had no upcoming bills for the past month, the next week or so will be a way for us to test things out, and I hope you'll continue to offer suggestions.

**Comment by carlossilva** [comment]
Absolutely, I can offer some testing as well as I work on migrating from the sunlight API to propublica.

**Comment by konklone** [comment]
Yeah, to add a bit -- the House doesn't always specify specific dates bills will be considered. 

For example, the House does have something up now, for the week of September 4th: http://docs.house.gov/floor/

My recommendation is to just display everything in the present or future (the current day or any day following), since it will never be a tremendously huge amount of things, and let clients filter that down as desired. 

Also, if you ask for a chamber in the URL, support for `both` would be awesome, along with a specific `chamber` field where the bill is being considered, per-bill. (Even if the future of Senate upcoming bills is unclear, at least you can just add them and clients will automatically pick them right up.)

**Comment by dwillis** [comment]
Ok, thanks. These responses will be about as close to the Sunlight ones as anything we've added, I think, so doing this shouldn't be hard. For Senate, I'm switching from Dems to GOP, but essentially the same info.

**Comment by pcraciunoiu** [comment]
Hey there, another sunlight API user here :)

I see [talk](https://github.com/propublica/congress-api-docs/issues/8#issuecomment-326091617) about the upcoming bills feature being ready today, but I don't see it in [the](https://projects.propublica.org/api-docs/congress-api/other/) [documentation](https://projects.propublica.org/api-docs/congress-api/bills/). I'll follow this issue now, would be great to see it closed or get notified once it's ready t ouse.

**Comment by dwillis** [comment]
Not yet - gonna be ready on Tuesday.

**Comment by dwillis** [comment]
@pcraciunoiu It's ready tonight (for the House): https://api.propublica.org/congress/v1/bills/upcoming/house.json

**Comment by pcraciunoiu** [comment]
Thanks @dwillis works great. When do you estimate you'd be adding it for the senate?

**Comment by dwillis** [comment]
The Senate *should* update tonight.
