### ISSUE TITLE
RollCallVote Identifiable Values

### ISSUE THREAD

**Issue by jden1705** [propublica/congress-api-docs#82]
Assuming I'm reading the documentation correctly, to construct a rollCallVote URI and get the correct vote you need the following fields: 

- Congress number
- chamber name
- session number
- roll call number

When using the specific Bill endpoint there is no session field returned for either the bill or its specific votes. Can we include the session field within the votes list in the Specific Bill Endpoint? 

Other than on Vote records is there any other use for the session value? Doesn't seemed to be used elsewhere. 
Thanks.

**Comment by konklone** [comment]
FWIW, the session can be reliably calculated from the year, odd years being session 1 and even years being session 2.

**Comment by jden1705** [comment]
Oh cool. Would that be the year of the Roll Call Vote, or the year of the Bill?

**Comment by konklone** [comment]
The year of the roll call vote.

**Comment by jden1705** [comment]
thanks
