### ISSUE TITLE
Using HTML encoding in commitee names

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#84]
At least on the hearings endpoint, I get this:

```json
"committee": "Committee on Veterans&#39; Affairs"
```

HTML encoding can be done on clients as needed - the API should provide the characters and let clients perform the necessary escaping in their own environments.

**Comment by dwillis** [comment]
This should be fixed now.

**Comment by konklone** [comment]
Confirmed, and thank you!
