### ISSUE TITLE
Provide a boolean for passage/failure of vote on bill

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#85]
Right now, the `result` field on a bill vote is the text shown in the source document. This can be `Passed`, `Failed`, `Bill Passed`, or other text values.

Having a clear boolean "did it pass or fail?" field would be helpful to clients who want to branch logic based on that condition.

**Comment by dwillis** [comment]
This would only be for votes on passage, yes? Null for all other cases? What about amendments?

**Comment by konklone** [comment]
I think it would be for votes that were "successful", and which cleared their threshold. Though honestly, 3 weeks later, after wrestling through vote code, I no longer remember how I'd use this value, so it's low priority from me.
