### ISSUE TITLE
Bills search endpoint using a page size of 10 instead of 20

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#86]
The bill search endpoint says:

> Use this request to search the title and full text of legislation by keyword to get the 20 most recent bills.

But the endpoint is returning 10 bills at a time. 

It would be very helpful from a client standpoint to adjust the behavior to 20, rather than adjusting the documentation to 10.

**Comment by konklone** [comment]
Also, attempting to use an `offset` of `10` gives me this error, reinforcing that it should be doing 20 bills at a time instead of 10:

```json
{"status":"ERROR","copyright":"Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.","errors":"Offset needs to be a multiple of 20"}
```

**Comment by jeremybmerrill** [comment]
see #74.
