### ISSUE TITLE
API says a bill has been enacted, when it is not yet enacted

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#89]
This seems like a small but significant bug - the API says that HR 3364 has been "enacted", but it has not yet been signed by the President.

From https://api.propublica.org/congress/v1/115/bills/hr3364.json -

```json
         "introduced_date": "2017-07-24",
         "active": true,
         "house_passage": "2017-07-24",
         "senate_passage": "2017-07-26",
         "enacted": "2017-07-27",
```

And on [its page on Congress.gov](https://www.congress.gov/bill/115th-congress/house-bill/3364) as of right now:

![screenshot from 2017-07-29 22-11-32](https://user-images.githubusercontent.com/4592/28750025-e69c259a-74aa-11e7-86dc-876cb46807a1.png)

**Comment by dwillis** [comment]
Thanks, @konklone, this is fixed now.
