### ISSUE TITLE
Broken Senate source vote URLs

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#91]
The `source` fields for Senate votes use URLs like this:

```
http://senate.gov/legislative/LIS/roll_call_votes/vote1151/vote_115_1_00035.xml
```

But any `http://senate.gov` URL redirects to the root `https://www.senate.gov`, and so this URL is broken.

Instead, URLs should begin with `https://www.` This works:

https://www.senate.gov/legislative/LIS/roll_call_votes/vote1151/vote_115_1_00035.xml

**Comment by dwillis** [comment]
This is fixed now.

**Comment by konklone** [comment]
Confirmed, and thank you!
