### ISSUE TITLE
Update Senate vote URLs to use HTTPS

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#92]
The `url` field on Senate votes uses plain `http://`, but the Senate now uses `https://` -

> http://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?congress=115&session=1&vote=00035

Redirects to:

> https://www.senate.gov/legislative/LIS/roll_call_lists/roll_call_vote_cfm.cfm?congress=115&session=1&vote=00035

The API should use the `https://` URLs and eliminate the need for insecure redirects.

**Comment by dwillis** [comment]
This should be fixed now.

**Comment by konklone** [comment]
Confirmed, and thank you!
