### ISSUE TITLE
start-date/end-date form of votes endpoint not documented

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#94]
The [Votes by Date endpoint](https://projects.propublica.org/api-docs/congress-api/endpoints/#get-votes-by-date) describes a URL format where you can specify a date range instead of a specific month:

> You can get all votes in a particular month, or all votes in a particular date range (fewer than 30 days). This request type has two URI structures. Either use a year and month combination or a range of two dates, which cannot exceed 30 days.

And the `start-date` and `end-date` fields are documented below that, but only one URI structure is documented:

```
GET https://api.propublica.org/congress/v1/{chamber}/votes/{year}/{month}.json
```

What is the other URL format?

**Comment by konklone** [comment]
It appears to be:

```
GET https://api.propublica.org/congress/v1/{chamber}/votes/{start-date}/{end-date}.json
```

I guessed and that seems to work. So, my request is that it be documented explicitly.

**Comment by dwillis** [comment]
This is done.

**Comment by konklone** [comment]
Thank you!
