### ISSUE TITLE
Allow vote endpoints to use 'both' for chamber

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#95]
Instead of getting only X days' worth of `senate` votes or `house` votes, allow votes from `both` chambers to be returned in one combined list.

**Comment by dwillis** [comment]
This should be working now. Try https://api.propublica.org/congress/v1/both/votes/2017-01-03/2017-01-31.json or https://api.propublica.org/congress/v1/both/votes/2017/01.json

**Comment by konklone** [comment]
Confirmed, thank you!
