### ISSUE TITLE
Put amendment details on (at least Senate) votes

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#96]
The vote lists have `bill` objects with `title` and `bill_id` fields, which is very helpful at displaying context around a vote.

The Senate has amendment information associated with a vote, which would be helpful to include in an `amendment` field. For example:

https://www.senate.gov/legislative/LIS/roll_call_votes/vote1151/vote_115_1_00017.xml

```xml
<amendment>
<amendment_number>S.Amdt. 179</amendment_number>
<amendment_to_amendment_number/>
<amendment_to_amendment_to_amendment_number/>
<amendment_to_document_number>S.Con.Res. 3</amendment_to_document_number>
<amendment_to_document_short_title>No short title on file</amendment_to_document_short_title>
<amendment_purpose>
To establish a deficit-neutral reserve fund relating to reforming housing and Medicaid without prioritizing able-bodied adults over the disabled or raiding the Medicare Trust Funds to pay for new government programs, like Obamacare, which has failed Americans by increasing premiums and reducing affordable health care opportunities.
</amendment_purpose>
</amendment>
```

Getting the amendment ID, associated bill ID, and amendment purpose onto the vote object in vote list endpoints would be very helpful for clients wanting to show what a vote was about.

**Comment by dwillis** [comment]
@konklone The amendment purpose is already displayed in the `description` attribute of vote responses, and they also have associated bill information, too. Adding the amendment ID seems like a no brainer.

**Comment by dwillis** [comment]
@konklone Ok, I've added an `amendment` attribute for House and Senate votes - the latter works fine, but there are a number of House amendments that it is not possible to programmatically connect them to their actual amendment object due to the way that the House identifies them in vote data. Thoughts on how to handle these?

**Comment by konklone** [comment]
> @konklone Ok, I've sketched out an amendment attribute for House and Senate votes - the latter works fine, but there are a number of House amendments that it is not possible to programmatically connect them to their actual amendment object due to the way that the House identifies them in vote data. Thoughts on how to handle these?

We used to connect these at Sunlight by cross-referencing data sources, using the unitedstates bill data gatherer and the House vote data:

* Bill parser (uses USGPO collection) runs through amendment sub-objects: https://github.com/unitedstates/congress/blob/master/tasks/bills.py#L221-L222

* Amendment parser saves the House number field, while also saving a globally unique ID for the amendment: https://github.com/unitedstates/congress/blob/master/tasks/amendment_info.py#L90-L94

* Amendment loader looks for the `house_number` field and store it on the amendment before saving it: https://github.com/propublica/sunlight-congress/blob/master/tasks/amendments/amendments.rb#L98-L100

* House vote loader looks up a globally unique amendment ID from the amendments table by looking up the amendment by the relative ID: https://github.com/propublica/sunlight-congress/blob/master/tasks/votes_house/votes_house.rb#L153-L164

I left Sunlight before the THOMAS->USGPO switch happened, so I never fully validated the current stack, but the general approach should still be sound.

**Comment by dwillis** [comment]
That general approach is solid, but it's not perfect. For example, take House vote 431 this year, on an amendment from Brendan Boyle: http://clerk.house.gov/evs/2017/roll431.xml

The House vote data only refers to it as No. 12, while the [GPO file](https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/115/hr/BILLSTATUS-115hr3219.xml) assigns it number 261 and makes no reference to No. 12 in the amendment description, as it does for other amendments. In my tests, there are > 100 House amendments in this situation in the current Congress.

**Comment by dwillis** [comment]
We've added this, with the caveat that not every amendment vote will have those details due to the issue above. I've opened [an issue with the GPO](https://github.com/usgpo/bill-status/issues/70) and will see what they say.

**Comment by konklone** [comment]
Thank you!
