### ISSUE TITLE
Put a little detail about voters on the positions list for a specific vote

### ISSUE THREAD

**Issue by konklone** [propublica/congress-api-docs#97]
On the specific vote endpoint, you get fairly minimal information about specific votes, just the bioguide ID, the vote, and a DW Nominate score:

```json
"positions": [
              {
                "member_id": "A000360",
                "vote_position": "Yes",
                "dw_nominate": 0.323
              }
```

For those clients who don't keep local databases of members and are trying to build UIs based on the information in as small a number of requests as possible, having enough information to display member names/parties/states/districts would be helpful.

**Comment by dwillis** [comment]
We've added `name`, `party`, `state` and, for house votes, `district` to the vote responses.

**Comment by konklone** [comment]
Verified, and this totally resolves my issue. Thank you!
